### ISSUE TITLE
IPsec not working - Please help urgent request !

### ISSUE THREAD

**Issue by ashutosh1701204** [xelerance/Openswan#103]
[root@redhat-1 ~]# ipsec auto --up myconnect
022 "myconnect": We cannot identify ourselves with either end of this connection
We have the same configuration on both gateway severs.

Once this setup works we need to setup IPsec tunnel between CentOS 7 machine and Checkpoint.
Please send KB article or let us know how can we achieve this.
[root@redhat-1 ~]# more /etc/ipsec.d/ipsec.conf
conn myconnect
        type=tunnel
        left=104.155.211.218
        leftsubnet=10.240.0.0/16
        right=104.155.216.232
        rightsubnet=10.240.0.0/16
        keyexchange=ike
        auth=esp
        auto=start
        authby=secret
        ike=aes256-sha1-modp2048
        esp=aes256-sha1
root@redhat-1 ~]# ipsec verify
Checking your system to see if IPsec got installed and started correctly:
Version check and ipsec on-path                                 [OK]
Linux Openswan U2.6.32/K2.6.32-504.3.3.el6.x86_64 (netkey)
Checking for IPsec support in kernel                            [OK]
 SAref kernel support                                           [N/A]
 NETKEY:  Testing for disabled ICMP send_redirects              [OK]
NETKEY detected, testing for disabled ICMP accept_redirects     [OK]
Testing against enforced SElinux mode                           [OK]
Checking that pluto is running                                  [OK]
 Pluto listening for IKE on udp 500                             [OK]
 Pluto listening for NAT-T on udp 4500                          [OK]
Checking for 'ip' command                                       [OK]
Checking /bin/sh is not /bin/dash                               [OK]
Checking for 'iptables' command                                 [OK]
Opportunistic Encryption Support                                [DISABLED]
[root@redhat-1 ~]#

**Comment by letoams** [comment]
On Fri, 15 Jun 2018, Dinuka Salwathura wrote:

> I am running Libreswan 3.23 on Cent OS 7 on google cloud,

So this question really belongs to the libreswan github repository,
not the old openswan legacy code.

> conn ez-cash

>     leftsourceip=35.229.xx.xx
>     left=10.142.0.4
>     leftsubnet=10.142.0.0/24

leftsourceip should be an ip from your leftsubnet. The one that's on
the libreswan machine itself.

You also need to ensure traffic from leftsubnet to rightsubnet is not
NAT'ed by accident.

Paul

**Comment by dinukasal** [comment]
Thank you for the response,
unfortunately traffic is NAT'ed, so I cannot use libreswan if traffic is NAT'ed?

**Comment by letoams** [comment]
> On Jun 16, 2018, at 02:42, Dinuka Salwathura <notifications@github.com> wrote:
> 
> Thank you for the response,
> unfortunately traffic is NAT'ed, so I cannot use libreswan if traffic is NAT'ed?
> 

Of course you can, you need to exclude those from NAT using iptables. See the libreswan FAQ

**Comment by dinukasal** [comment]
This is the output of "watch -n0.5 ipsec status"
https://dinukasthoughts.wordpress.com/2018/06/16/libreswan-log/

**Comment by shussain** [comment]
@dinukasal as you have noted, this issue is on Libreswan. 

As such, I will locking this closed issue. If you have any Openswan specific issues, please feel free to open a new issue
