### ISSUE TITLE
We cannot identify ourselves with either end of this connection. Please help urgent !

### ISSUE THREAD

**Issue by ashutosh1701204** [xelerance/Openswan#105]
Please refer below configuration , we are creating IPsec tunnel between Centos 6 machine having openswan and Checkpoint.

[root@vpn-gateway ~]# /usr/sbin/ipsec whack --name connect1  --listen --initiate
002 listening for IKE messages
002 forgetting secrets
002 loading secrets from "/etc/ipsec.secrets"
002 loading secrets from "/etc/ipsec.d/ipsec.secrets"
022 "connect1": We cannot identify ourselves with either end of this connection.

more /etc/ipsec.d/ipsec.conf 
conn connect1
        type=tunnel
        ikelifetime=1440m
        keylife=1440m
        authby=secret
        auto=start
        pfs=no
        keyexchange=ike
        ike=aes256-sha1;modp1024
        phase2alg=aes256-sha1;modp1024
        forceencaps=yes
        left=104.155.193.171
        leftsubnet=172.16.10.0/24 
        leftnexthop=%defaultroute
        right=116.112.90.117 
        rightsubnet=172.16.58.0/24
        rightnexthop=%defaultroute

**Comment by letoams** [comment]
On Mon, 5 Jan 2015, ashutosh1701204 wrote:

> Please refer below configuration , we are creating IPsec tunnel between Centos 6 machine having openswan and Checkpoint.
> 
> 022 "connect1": We cannot identify ourselves with either end of this connection.

> more /etc/ipsec.d/ipsec.conf
> conn connect1
> type=tunnel
> ikelifetime=1440m
> keylife=1440m
> authby=secret
> auto=start
> pfs=no
> keyexchange=ike
> ike=aes256-sha1;modp1024
> phase2alg=aes256-sha1;modp1024
> forceencaps=yes
> left=104.155.193.171
> leftsubnet=172.16.10.0/24
> leftnexthop=%defaultroute
> right=116.112.90.117
> rightsubnet=172.16.58.0/24
> rightnexthop=%defaultroute

So your machines does not have the IP address 104.155.193.171 or
116.112.90.117 configured. Or ipsec was started before those IPs
were configured. if that is the case, you can try:
ipsec whack --listen
ipsec auto --add connect1
ipsec auto --up connect1

Note that older versions of "addconn" acted badly with
rightnexthop=%defaultroute if you were left (and vise versa)

Paul

**Comment by ashutosh1701204** [comment]
Connection is up now , but we are not able to connect other side private network.
Any suggestion.
root@vpn-gateway ~]# service ipsec status
IPsec running  - pluto pid: 21247
pluto pid 21247
1 tunnels up
some eroutes exist

It seems we have on IPSec table
root@vpn-gateway ~]#  ipsec look 
vpn-gateway Tue Jan  6 08:19:54 UTC 2015
IPSEC TABLE
ROUTING TABLE
172.16.10.1 dev eth0  scope link 
115.112.91.117 via 172.16.10.117 dev eth0  scope link 
169.254.0.0/16 dev eth0  scope link  metric 1002 
default via 172.16.10.1 dev eth0  proto static

**Comment by letoams** [comment]
On Tue, 6 Jan 2015, ashutosh1701204 wrote:

> Connection is up now , but we are not able to connect other side private network.

check "ipsec verify"

ensure you do not NAT or MASQUERADE packets with src/dst of packets
meant for IPsec.

Try "ping -I internalip" instead of just ping?

Paul
