### ISSUE TITLE
failed to build notification for spisize=0, when doesn't support ESP algorithm

### ISSUE THREAD

**Issue by YafeiYan** [xelerance/Openswan#109]
I'm confused about this API send_notification_from_state(), it generates a notification packet sent to peer host who created this negotiation actively. But this notification packet will build failed due to spisize=0, and I look up this code fragment:

void send_notification_from_state(struct state *st, enum state_kind state,
    u_int16_t type)
{
    struct state *p1st;

    passert(st);

    if (state == STATE_UNDEFINED)
	state = st->st_state;

    if (IS_QUICK(state)) {
	p1st = find_phase1_state(st->st_connection, ISAKMP_SA_ESTABLISHED_STATES);
	if ((p1st == NULL) || (!IS_ISAKMP_SA_ESTABLISHED(p1st->st_state))) {
	    loglog(RC_LOG_SERIOUS,
		"no Phase1 state for Quick mode notification");
	    return;
	}
	send_notification(st, type, p1st, generate_msgid(p1st),
	    st->st_icookie, st->st_rcookie, NULL, 0, PROTO_ISAKMP);
    }
    else if (IS_ISAKMP_ENCRYPTED(state)) {
	send_notification(st, type, st, generate_msgid(st),
	    st->st_icookie, st->st_rcookie, NULL, 0, PROTO_ISAKMP);
    }
    else {
	/* no ISAKMP SA established - don't encrypt notification */
	send_notification(st, type, NULL, 0,
	    st->st_icookie, st->st_rcookie, NULL, 0, PROTO_ISAKMP);
    }
}

when the passive device doesn't support the ESP algorithm, it will build a notification about NO_PROPOSAL_CHOSEN, then sending it to peer. But in this code, the argument "spi_size" 
is 0 in default, so building the notification will be always failed.

**Comment by letoams** [comment]
On Thu, 22 Jan 2015, Yafei wrote:

> I'm confused about this API send_notification_from_state(), it generates a notification packet sent to peer host who created this
> negotiation actively. But this notification packet will build failed due to spisize=0, and I look up this code fragment:

You might want to look at the libreswan version of this code as we simplified things
a lot around the spi size handling code and the openswan code is three
years out of date.

> when the passive device doesn't support the ESP algorithm, it will build a notification about NO_PROPOSAL_CHOSEN, then sending it to peer.
> But in this code, the argument "spi_size"
> is 0 in default,

That is correct.

o  SPI Size (1 octet) - Length in octets of the SPI as defined by the
       IPsec protocol ID or zero if no SPI is applicable.  For a
       notification concerning the IKE SA, the SPI Size MUST be zero and
       the field must be empty.

Since you have no IPsec SA (because you cannot agree on ESP algo) you
only have an IKE/ISAKMP SA, so the spisize MUST be 0.

> so building the notification will be always failed.

Why does it fail?

Note that openswan does not properly support INVALID_KE use cases and
will return NO_PROPOSAL_CHOSEN by mistake. This was fixed in libreswan.

Paul

**Comment by YafeiYan** [comment]
Paul, Thanks! I will check Libreswan for reference. Do you go on updating Openswan code?

**Comment by letoams** [comment]
On Thu, 22 Jan 2015, Yafei wrote:

> Paul, Thanks! I will check Libreswan for reference. Do you go on updating Openswan code?

No, see:

https://nohats.ca/wordpress/openswan/

and

https://nohats.ca/wordpress/blog/2014/02/16/development-of-libreswan-vs-openswan/

Paul

**Comment by YafeiYan** [comment]
Thank you very much!
