### ISSUE TITLE
Openswan pending phase 2

### ISSUE THREAD

**Issue by shahran** [xelerance/Openswan#111]
Hello Openswan experts. I am having an issue with openswan. Please see the log below:

000 "tunnel0": 10.250.27.228/30===10.248.53.227<10.248.53.227>[@dst,+S=C]...10.252.255.186<10.252.255.186>[@miipsnet,+S=C]===10.0.0.0/8; prospective erouted; eroute owner: #0
000 "tunnel0":     myip=unset; hisip=unset; hisup=/etc/ipsec/ipsec_updown;
000 "tunnel0":   ike_life: 86400s; ipsec_life: 28800s; rekey_margin: 1200s; rekey_fuzz: 100%; keyingtries: 0
000 "tunnel0":   policy: PSK+ENCRYPT+TUNNEL+UP+IKEv2ALLOW+SAREFTRACK+lKOD+rKOD; prio: 30,8; interface: ppp0; 
000 "tunnel0":   dpd: action:clear; delay:60; timeout:60; 
000 "tunnel0":   newest ISAKMP SA: #0; newest IPsec SA: #0; 
000 "tunnel0":   IKE algorithms wanted: 3DES_CBC(5)_000-SHA1(2)_000-MODP1024(2), 3DES_CBC(5)_000-MD5(1)_000-MODP1024(2), AES_CBC(7)_128-SHA1(2)_000-MODP1024(2), AES_CBC(7)_000-MD5(1)_000-MODP1024(2); flags=-strict
000 "tunnel0":   IKE algorithms found:  3DES_CBC(5)_192-SHA1(2)_160-MODP1024(2), 3DES_CBC(5)_192-MD5(1)_128-MODP1024(2), AES_CBC(7)_128-SHA1(2)_160-MODP1024(2), AES_CBC(7)_128-MD5(1)_128-MODP1024(2)
000 "tunnel0":   ESP algorithms wanted: AES(12)_128-SHA1(2)_000; flags=-strict
000 "tunnel0":   ESP algorithms loaded: AES(12)_128-SHA1(2)_160
000  
000 #1: "tunnel0":500 STATE_MAIN_I1 (sent MI1, expecting MR1); EVENT_RETRANSMIT in 5s; nodpd; idle; import:admin initiate
000 #1: pending Phase 2 for "tunnel0" replacing #0

Here is my config

-------------------------------------------------------------------------------

# /etc/ipsec.conf - Openswan IPsec configuration file

# This file:  /usr/share/doc/openswan/ipsec.conf-sample
#
# Manual:     ipsec.conf.5

version 2.0     # conforms to second version of ipsec.conf specification

# basic configuration
config setup
        # Do not set debug options to debug configuration issues!
        # plutodebug / klipsdebug = "all", "none" or a combation from below:
        # "raw crypt parsing emitting control klips pfkey natt x509 dpd private"
        # eg:
        # plutodebug="control parsing"
        #
        # enable to get logs per-peer
        # plutoopts="--perpeerlog"
        #
        # Again: only enable plutodebug or klipsdebug when asked by a developer
        #
        # NAT-TRAVERSAL support, see README.NAT-Traversal
        nat_traversal=yes
        # exclude networks used on server side by adding %v4:!a.b.c.0/24
        virtual_private=%v4:10.0.0.0/8,%v4:10.250.27.228/30
        # OE is now off by default. Uncomment and change to on, to enable.
        oe=off
        nhelpers=0
        # which IPsec stack to use. auto will try netkey, then klips then mast
        protostack=klips
        klipsdebug=none
        overridemtu=1400
        #interfaces=%defaultroute

# Add connections here
conn %default
                type=tunnel
                keyexchange=ike
                ike=3des-sha1-modp1024,3des-md5-modp1024,aes128-sha1-modp1024,aes-md5-modp1024
                ikelifetime=24h
                keylife=8h
                rekey=yes
                rekeymargin=20m
                keyingtries=%forever
                auth=esp
                authby=secret
                esp=aes128-hmac_sha1
                right=10.252.255.186
                rightid=@miipsnet
                rightupdown=/etc/ipsec/ipsec_updown
                pfs=no
                dpddelay=60
                dpdtimeout=60
                dpdaction=clear
                disablearrivalcheck=yes
                failureshunt=drop

conn block
        auto=ignore

conn private
        auto=ignore

conn private-or-clear
        auto=ignore

conn clear-or-private
        auto=ignore

conn clear
  auto=ignore

conn packetdefault
  auto=ignore

# sample VPN connection
# for more examples, see /etc/ipsec.d/examples/

conn tunnel0
conn tunnel0
#               # Left security gateway, subnet behind it, nexthop toward right.
        left=10.248.53.227
        leftid=@dst
        leftsubnet=10.250.27.228/30
#       leftnexthop=
#               # Right security gateway, subnet behind it, nexthop toward left.
        right=10.252.255.186
        rightsubnet=10.0.0.0/8
#               rightnexthop=10.101.102.103
#               # To authorize this connection, but not actually start it,
#               # at startup, uncomment this.
         auto=start

**Comment by MalathiKamath** [comment]
Hello,
I too face this issue with my similar setup. Both ends are running on RhEL and openswan v2.6.32
Please let me know if this is fixed in later versions

**Comment by shussain** [comment]
This issue has been fixed with latest OSW
