### ISSUE TITLE
about the algorithm specified

### ISSUE THREAD

**Issue by kingseng824** [xelerance/Openswan#112]
We know in the file ipsec.conf, if we type ike = aes-sha1 ,esp = 3des-sha1, then AES and SHA1 will be used for the connection in phase1, 3des and sha1 will be used for a phase2 negotiation.And also when we transmit data , the data will be encrypted using 3des.

But if we type ike = aes-sha1 and don't type anything about esp in ipsec.conf, what algorithm will be used in phase2 and data transmission. 
Thank you !

**Comment by mcr** [comment]
It depends upon the exact version and flavour of *swan, and also what the policy at the other end is, but AES128 with SHA1 is usually the default. Some older versions still favour MD5, some newer versions prefer SHA2.  The selected algorithm is logged.
