### ISSUE TITLE
Working VPC Example

### ISSUE THREAD

**Issue by robgil** [xelerance/Openswan#117]
Hey Folks,

I've spent the last 3 days trying to get openswan to work fully with the AWS VPC VPN.

What works:
-Can initiate connections and am able to hit their 169.254.\* zeroconf addresses that they use for p2p vpns.
-Can ping the other side (169.x) and push bgp routes to the peer

What doesnt:

```
Mar  6 23:17:51 ip-10-0-1-20 pluto[2321]: "aws1/2x2" #1: received Delete SA payload: replace IPSEC State #24 in 10 seconds
Mar  6 23:17:51 ip-10-0-1-20 pluto[2321]: "aws1/2x2" #1: received and ignored empty informational notification payload
Mar  6 23:17:51 ip-10-0-1-20 pluto[2321]: "aws1/2x2" #1: received Delete SA payload: replace IPSEC State #25 in 10 seconds
Mar  6 23:17:51 ip-10-0-1-20 pluto[2321]: "aws1/2x2" #1: received and ignored empty informational notification payload
```

They appear to kick out anything that isnt their 169.\* addresses in the 'rightsubnets=' section.

Traffic goes over for all of about 10 seconds until the tunnel is reset(?). 

The peer also wants to send me default routes...

```
Mar  5 17:36:59 ip-10-0-1-20 pluto[2214]: "aws1/1x1" #3: the peer proposed: 0.0.0.0/0:0/0 -> 0.0.0.0/0:0/0
```

If I try to add them to rightsubnets= it conflicts with the default route on the box and I lose connectivity (reboot for the win). 

I've tried passthroughs but those seem to still disconnect me. 

I'll post configs etc if this is possible to do with netkey. If its not really possible to do 'routed' tunnels with netkey, and perhaps klips is the way to go, ill switch it up and try that.

The path is the following
10.0.0.0/16 => 169.254.1.1/30 => Elastic IP => internet => AWS Public IP => 169.254.1.2/30 => Every other vpc network

**Comment by benkoller** [comment]
Sorry to dig up this ancient issue, any success in your efforts ever since?

**Comment by letoams** [comment]
On Tue, 6 Oct 2015, benkoller wrote:

> Sorry to dig up this ancient issue, any success in your efforts ever since?

You might want to look at:

https://libreswan.org/wiki/Interoperability#Amazon_AWS_VPN

https://libreswan.org/wiki/High_Availability_/_Failover_VPN_in_AWS_using_libreswan

Paul
