### ISSUE TITLE
Phase 2 negotiation fails between 2  machines using v2.6.32 openswan

### ISSUE THREAD

**Issue by MalathiKamath** [xelerance/Openswan#119]
Hi All,
I am using 2 linux machines where ipsec is setup, but after sometime tunnel goes down with phase 2 failing to negotiate.  Takes about 40 mins to recover the tunnel automatically. Is this known issue ? Do we have fix in later versions?Kindly respond.

**Comment by shussain** [comment]
One can use dpd code. In addition the rekey code has been upgraded. Please try with the latest version of OSW
