### ISSUE TITLE
NULL Encryption Algorithm (question)

### ISSUE THREAD

**Issue by kronikl** [xelerance/Openswan#121]
Hello,
I installed openswan+xl2tpd (ubuntu 12.04 LTS). It works.
I want to start IPSec without encryption.All articles speak that it's possible, but none of what setting it makes.
Answer my question, please:
What should I write in the config to disable the encryption of traffic?

It's my config:

config setup
        nat_traversal=yes
        virtual_private=%v4:10.0.0.0/24
        oe=off
        protostack=netkey

conn L2TP-PSK-NAT
        rightsubnet=vhost:%priv
        also=L2TP-PSK-noNAT

conn L2TP-PSK-noNAT
        authby=secret
        pfs=no
        auto=add
        keyingtries=3
        rekey=no
        dpddelay=30
        dpdtimeout=120
        dpdaction=clear
        ikelifetime=8h
        keylife=1h
        type=transport
        left=My-IP-adress
        leftprotoport=17/1701
        right=%any
        rightprotoport=17/%any
        forceencaps=yes

**Comment by mcr** [comment]
kronikl <notifications@github.com> wrote:
    > I installed openswan+xl2tpd (ubuntu 12.04 LTS). It works.
    > I want to start IPSec without encryption.All articles speak that it's
    > possible, but none of what setting it makes.
    > Answer my question, please:
    > What should I write in the config to disable the encryption of
    > traffic?

Why?  Are you after AH?
You mention using L2TP as well.  

    > conn L2TP-PSK-noNAT
    > authby=secret
    > pfs=no
    > auto=add
    > keyingtries=3
    > rekey=no
    > dpddelay=30
    > dpdtimeout=120
    > dpdaction=clear
    > ikelifetime=8h
    > keylife=1h
    > type=transport
    > left=My-IP-adress
    > leftprotoport=17/1701
    > right=%any
    > rightprotoport=17/%any
    > forceencaps=yes

you need specify:
    phase2alg=null-sha1

I think.  I've never tested it myself.  As I recall, KLIPS does not support
NULL encryption, and if you really want L2TP, then you may need the SAREF
support.

-- 
]               Never tell me the odds!                 | ipv6 mesh networks [ 
]   Michael Richardson, Sandelman Software Works        | network architect  [ 
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by kronikl** [comment]
Hello.
Thanks for quick response!
I try setting which you recommend.
You write about L2TP how not good choice.
I describe my task, may be you'll recommend anything.
I need VPN with security authentication. Clients must see each others. Traffic must be without encryption, because it is not a secret. And it doesn't require a lot of computing power.
For these purposes, I installed and configured server with L2TP+IPSec. Everything works as it should, I need only have to disable encryption.
Now this is a problem for me. Maybe you can suggest another solution to my problem.
Thanks in advance.

**Comment by mcr** [comment]
kronikl <notifications@github.com> wrote:
    > I try setting which you recommend.
    > You write about L2TP how not good choice.
    > I describe my task, may be you'll recommend anything.
    > I need VPN with security authentication. Clients must see each others.

Why does it mean for client to see each other?  Do you mean that they need to
be able exchange traffic, or do you mean that all clients must see all
traffic from other clients?

    > Traffic must be without encryption, because it is not a secret. And it
    > doesn't require a lot of computing power.

Unless you are dealing with very old technology, the cost of encryption is
not very high.  In general, NULL encryption is used for diagnosing problems.
Some distros do not even ship it with their kernel.

**Comment by kingseng824** [comment]
if you don't type ike=aes-sha1 in ipsec.conf,it will chose the first combination of algorithms available in spdb.c.
here is my combination in spdb.c
static struct db_trans oakley_trans_rsasig[] = {
	{ AD_TR(KEY_IKE,otrsasig2048aessha1) },
	{ AD_TR(KEY_IKE,otrsasig2048aesmd5) },
	{ AD_TR(KEY_IKE,otrsasig2048des3sha1) },
	{ AD_TR(KEY_IKE,otrsasig2048des3md5) },
	{ AD_TR(KEY_IKE,otrsasig1536aessha1) },
	{ AD_TR(KEY_IKE,otrsasig1536aesmd5) },
	{ AD_TR(KEY_IKE,otrsasig1536des3sha1) },
	{ AD_TR(KEY_IKE,otrsasig1536des3md5) },
	{ AD_TR(KEY_IKE,otrsasig1024des3sha1) },
	{ AD_TR(KEY_IKE,otrsasig1024des3md5) },
	{ AD_TR(KEY_IKE,otrsasig1024aessha1) },
	{ AD_TR(KEY_IKE,otrsasig1024aesmd5) },
the  defination of otrsasig2048aessha1  is
static struct db_attr otrsasig2048aessha1[] = {
	{ .type.oakley=OAKLEY_ENCRYPTION_ALGORITHM, .val=OAKLEY_AES_CBC },
	{ .type.oakley=OAKLEY_HASH_ALGORITHM, .val=OAKLEY_SHA1 },
	{ .type.oakley=OAKLEY_AUTHENTICATION_METHOD, .val=OAKLEY_RSA_SIG },
	{ .type.oakley=OAKLEY_GROUP_DESCRIPTION, .val=OAKLEY_GROUP_MODP2048 },
	{ .type.oakley=OAKLEY_KEY_LENGTH, .val=128 },
	};
if it can be available,it will use AES_CBC to encrypt.
