### ISSUE TITLE
How enable Klips for Openswan in Centos7

### ISSUE THREAD

**Issue by vdv85** [xelerance/Openswan#123]
Hi. Please, help configure openswan with support klips in Centos7. In Default Openswan use Netkey, but it's not work for users in one network behind NAT to one enternal ip and  need prostack=klips.
I have: 
Linux 3.10.0-229.1.2.el7.x86_64
Linux Libreswan 3.12 (netkey)

Sorry for my English

**Comment by shussain** [comment]
Closing since it was about Libreswan
