### ISSUE TITLE
Pluto: SHA2 not supported in FIPS mode with NSS

### ISSUE THREAD

**Issue by JiriZendulka** [xelerance/Openswan#125]
Hello,

I use pluto with NSS library in FIPS mode. When I set hash sha256 or sha512 pluto reports: SHA2 not supported in FIPS mode with NSS. I think that NSS supports this hash algorithms in fips mode too. I have not found any information on NSS website or in NSS source files that sha256 or sha512 should be disallowed in fips mode.
Could someone clarify me why this hash algorithm is blocked in fips mode by pluto?

Thanks

**Comment by letoams** [comment]
On Wed, 13 May 2015, JiriZendulka wrote:

> I use pluto with NSS library in FIPS mode. When I set hash sha256 or sha512 pluto reports: SHA2 not supported in FIPS mode with NSS. I
> think that NSS supports this hash algorithms in fips mode too. I have not found any information on NSS website or in NSS source files that
> sha256 or sha512 should be be disallowed in fips mode.
> Could someone clarify me why this hash algorithm is blocked in fips mode by pluto?

Looks like a bug. libreswan allows sha256 in FIPS mode and so does NSS.

Paul

**Comment by JiriZendulka** [comment]
Hi Paul,

thanks for your comment. At openswan/lib/lib/openswan/alg_info.c (row 658) you can find a condition which block using sha2 in FIPS mode with NSS. I dont know from what reason....

Thanks.
Jiri

**Comment by letoams** [comment]
there is a lot more wrong in fips mode there too. openswan has like four copies of the PRF() function, it allows twofish and serpent for IKE in FIPS mode, etc etc etc. If you are looking at certification, you should probably stick to the certified version of openswan for RHEL6 or the certified version of libreswan in RHEL7

**Comment by JiriZendulka** [comment]
Yes,  I am looking for FIPS ready/compatibile solution...

Thanks.
Jiri

**Comment by mcr** [comment]
If FIPS/NIST/NSA compliance is important to you, then the Redhat version of libreswan is your best bet.
The NSS code that Paul (letoams) contributed to openswan has been an ongoing source of issues, and it is good that he has been able to work out those issues in the libreswan code base.

**Comment by letoams** [comment]
For the record, I did not contribute the code. The code came from Red Hat via Avesh. I did accept it and merged it into openswan when I was the release manager before I became a Red Hat Associate.

Paul

**Comment by JiriZendulka** [comment]
Hi Paul, Michael

I currently use openswan 2.6.4. and I need a solution which passes FIPS certification. So do you suggest to use libreswan instead of openswan? I found some src rpms at git.centos.org/projec/rpms/libreswan...


Thanks
Jiri

**Comment by letoams** [comment]
On Wed, 13 May 2015, JiriZendulka wrote:

> Subject: Re: [Openswan] Pluto: SHA2 not supported in FIPS mode with NSS (#125)
> 
> I currently use openswan 2.6.4. and I need a solution which passes FIPS certification. So do you suggest to use libreswan instead of
> openswan? I found some src rpms at git.centos.org/projec/rpms/libreswan...

(note: I am the redhat rhel6 openswan maintainer and rhel7 libreswan
maintainer)

I don't recommend anyone to run openswan anymore. It is not really being
developed anymore:  https://nohats.ca/swan.gif
The current version is not safe to use with NSS enabled and the custom
crypto code when not using NSS has never been audited or certified in
its lifetime of about 20 years (that I'm aware of)

If you do need to run a FIPS validated version, you're only option now
is to run openswan on RHEL6.5. There will be a FIPS update for openswan
on RHEL6.6 in the near future.

If you don't care about formal FIPS certification, but just want the
best code, you should run: https://download.libreswan.org/fips/

That package is currently undergoing FIPS certification for RHEL7, and has passed
other tests such as TAHI and USGv6. It also runs the NIST CAVS tests
during the rpmbuild of the package, and runs various CBC, CTR and GCM
test vectors on startup.

Paul

**Comment by JiriZendulka** [comment]
Hi Paul,

thank you very much for your answers and your time. There are very usefull informations from me. I need FIPS certification for our solution. I use openswan with NSS library (3.17.4) in FIPS mode . Our crypto modul runs at armv7 platfrom on embeded linux (kernel 3.12.10). Source files for correct version of openswan can I download from http://ftp.redhat.com/redhat/linux/enterprise/6Server/en/os/SRPMS/ ? Openswan 2.6.32-37 is the correct one?

Thanks
Jiri

**Comment by letoams** [comment]
On Thu, 14 May 2015, JiriZendulka wrote:

> thank you very much for your answers and your time. There are very usefull informations from me. I
> need FIPS certification for our solution. I use openswan with NSS library (3.17.4) in FIPS mode . Our
> crypto modul runs at armv7 platfrom on embeded linux (kernel 3.12.10). Source files for correct
> version of openswan can I download from
> http://ftp.redhat.com/redhat/linux/enterprise/6Server/en/os/SRPMS/ ? Openswan 2.6.32-37 is the
> correct one?

The latest one is not neccessarilly FIPS certified.

The latest document I see is:

http://csrc.nist.gov/groups/STM/cmvp/documents/140-1/140sp/140sp1859.pdf

which refers to 2.6.32-18.el6_3. I am not sure if there is an updated
version to that.

As I said, a new openswan for RHEL6 is coming out soon with updated FIPS
certification.

Note that technically, the FIPS certification is only valid on RHEL, and
not on your armv7 embedded platform. So I would recommend sticking with
the latest updated openswan package for RHEL6 for that reason, provided
you remain with openswan. It was FIPS certified and than saw only security
updates and import bug fixes.

Personally, I would of course use the libreswan package I provided to
you. It's IKEv2 stack is far far superior, as is its NSS support, and
it has NIST CAVS testing needed to pass FIPS.

Paul
