### ISSUE TITLE
Remote access client software (Windows) for IPSec VPN

### ISSUE THREAD

**Issue by kiransalunkhe** [xelerance/Openswan#126]
Please suggest me which free software (for windows) is available for remote access client of IPSec VPN (Openswan)?

**Comment by Khsed4** [comment]
@kiransalunkhe  I have the same issue, Did you find the answer?

**Comment by kiransalunkhe** [comment]
I have not tried, but heard about softether vpn client.

**Comment by letoams** [comment]
The built-in IKEv2 VPN comes with Windows for the last 10 years? (At least since Windows 6)

**Comment by Khsed4** [comment]
@letoams  I think u misunderstood the question since we need to implement the VPN programmatically, not by window setup.
