### ISSUE TITLE
OpenSwan DoD connection?

### ISSUE THREAD

**Issue by cjalaniz** [xelerance/Openswan#128]
Im trying to set up a home vpn server using https://raymii.org/s/tutorials/IPSEC_L2TP_vpn_on_a_Raspberry_Pi_with_Arch_Linux.html

But It fails to connect
but I noticed this 
Jun 09 16:51:47 alarmpi pluto[3965]: "L2TP-PSK"[6] 66.87.121.89 #15: the peer proposed: 70.116.104.140/32:17/1701 -> 26.217.55.89/32:17/1701  <<<<<<-------- DoD ip address???????
Jun 09 16:51:47 alarmpi pluto[3965]: "L2TP-PSK"[6] 66.87.121.89 #15: NAT-Traversal: received 2 NAT-OA. using first, ignoring others
Jun 09 16:51:47 alarmpi pluto[3965]: "L2TP-PSK"[6] 66.87.121.89 #17: responding to Quick Mode proposal {msgid:02000000}
Jun 09 16:51:47 alarmpi pluto[3965]: "L2TP-PSK"[6] 66.87.121.89 #17:     us: 192.169.1.116<192.169.1.116>:17/1701
Jun 09 16:51:47 alarmpi pluto[3965]: "L2TP-PSK"[6] 66.87.121.89 #17:   them: 192.169.1.1---66.87.121.89[26.217.55.89]:17/1701
Jun 09 16:51:47 alarmpi pluto[3965]: "L2TP-PSK"[6] 66.87.121.89 #17: keeping refhim=4294901761 during rekey
Jun 09 16:51:47 alarmpi pluto[3965]: "L2TP-PSK"[6] 66.87.121.89 #17: transition from state STATE_QUICK_R0 to state STATE_QUICK_R1
Jun 09 16:51:47 alarmpi pluto[3965]: "L2TP-PSK"[6] 66.87.121.89 #17: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2

**Comment by letoams** [comment]
25/8 is used my Rogers and T-Mobile and others. It was added to virtual_private= years ago even before libreswan forked years ago.
 You must be running using and old ipsec.conf file

**Comment by mcr** [comment]
The part where the peer proposes an address will be the address (behind the NAT) of your client device.  A number of mobile operators, having run out of RFC1918 addresses (10/8, 172.16/20, 192.168/16), started using address space internally that they thought would never appear on the live Internet.  So in this case, your mobile operator appears to have re-used the DoD addresses, thinking that those addresses will never appear on the live Internet.
As Paul says, in order for those addresses to be permitted, they need to be defined in the virtualip= as a range that is considered "private".
