### ISSUE TITLE
Anybody knows Route-Based IPsec on OpenSWAN

### ISSUE THREAD

**Issue by AlexSH-NET** [xelerance/Openswan#131]
Anybody knows how to do or have some documents?
Please help me, thanks.

**Comment by mcr** [comment]
Not really sure what Route-Based IPsec is.
Maybe you could explain what you are trying to do.

**Comment by AlexSH-NET** [comment]
Like i said in “Route-Based unsuccessfully #130”
https://github.com/xelerance/Openswan/issues/130

Route-Based IPsec means that ipsec tunnel have a ip address。 example： site-a‘s ipsec0 is 172.16.1.1/24 site-b’s ipsec0 is 172.16.1.2/24。

172.16.1.2 ping 172.16.1.1 successfully.  172.16.1.1 also ping 172.16.1.2 successfully。And IP-Packet pass through tunnel or not is determined by route。

I achieve Route-Based IPsec by self-define /etc/init.d/ipsec
 
This is my tunnel ：

[root@VPN ~]# ifconfig ipsec0
ipsec0    Link encap:Ethernet  HWaddr 52:54:00:54:CF:BE  
          inet addr:172.16.1.1  Mask:255.255.255.252
          inet6 addr: fe80::5054:ff:fe54:cfbe/128 Scope:Link
          UP RUNNING NOARP  MTU:1440  Metric:1
          RX packets:40125 errors:0 dropped:9 overruns:0 frame:0
          TX packets:40268 errors:0 dropped:88 overruns:0 carrier:0
          collisions:0 txqueuelen:10
          RX bytes:6214184 (5.9 MiB)  TX bytes:6646828 (6.3 MiB)

[root@NS2 ~]# ifconfig ipsec0
ipsec0    Link encap:Ethernet  HWaddr 52:54:00:0D:DC:6B  
          inet addr:172.16.1.2  Mask:255.255.255.252
          inet6 addr: fe80::5054:ff:fe0d:dc6b/128 Scope:Link
          UP RUNNING NOARP  MTU:1440  Metric:1
          RX packets:40381 errors:0 dropped:0 overruns:0 frame:0
          TX packets:40348 errors:0 dropped:4 overruns:0 carrier:0
          collisions:0 txqueuelen:10
          RX bytes:2825777 (2.6 MiB)  TX bytes:10074676 (9.6 MiB)

[root@VPN ~]# ping 172.16.1.2 -I 172.16.1.1
PING 172.16.1.2 (172.16.1.2) from 172.16.1.1 : 56(84) bytes of data.
64 bytes from 172.16.1.2: icmp_seq=1 ttl=64 time=102 ms
64 bytes from 172.16.1.2: icmp_seq=2 ttl=64 time=106 ms
64 bytes from 172.16.1.2: icmp_seq=3 ttl=64 time=106 ms
^C
--- 172.16.1.2 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2773ms
rtt min/avg/max/mdev = 102.963/105.307/106.687/1.708 ms

route -n | grep 172.16.1.2
10.8.0.0        172.16.1.2      255.255.0.0     UG    0      0        0 ipsec0
74.0.0.0        172.16.1.2      255.0.0.0       UG    0      0        0 ipsec0
8.0.0.0         172.16.1.2      255.0.0.0       UG    0      0        0 ipsec0

**Comment by mcr** [comment]
This looks like regular IPsec to me.

**Comment by letoams** [comment]
https://libreswan.org/wiki/Route-based_VPN_using_VTI

openswan does not support VTI

**Comment by AlexSH-NET** [comment]
@letoams thanks  0.0
