### ISSUE TITLE
Unable to establish tunnel FRAGMENTATION

### ISSUE THREAD

**Issue by eaparnell** [xelerance/Openswan#133]
I am following the Amazon EC2 example and am getting the following on the non AWS server:

Jul  1 15:44:55 hostname pluto[21915]: packet from <ip_address>:500 received Vendor ID payload [Dead Peer Detection]
Jul  1 15:44:55 hostname pluto[21915]: packet from <ip_address>:500 ignoring Vendor ID payload [FRAGMENTATION]
Jul  1 15:44:55 hostname pluto[21915]: packet from <ip_address>:500 received Vendor ID payload [RFC 3947] method set to=109 
Jul  1 15:44:55 hostname pluto[21915]: packet from <ip_address>:500 received Vendor ID payload [draft-ietf-ipsec-nat-t-ike-03] meth=108, but already using method 109
Jul  1 15:44:55 hostname pluto[21915]: packet from <ip_address>:500 received Vendor ID payload [draft-ietf-ipsec-nat-t-ike-02_n] meth=106, but already using method 109
Jul  1 15:44:55 hostname pluto[21915]: packet from <ip_address>:500 received Vendor ID payload [draft-ietf-ipsec-nat-t-ike-02] meth=107, but already using method 109
Jul  1 15:44:55 hostname pluto[21915]: packet from <ip_address>:500 initial Main Mode message received on <ip_address>:500 but no connection has been authorized with policy=PSK

Config for non-AWS host  is:
conn mytunnel
    left=<non-aws ip address>
    leftid=<non-aws ip address>
    rightid=<aws elastic ip>
    right=<aws elastic ip>
    rightnexthop=%defaultroute
    authby=secret
    rekey=no
    # load and initiate automatically
    auto=add

Config for AWS host is:

conn mytunnel
    left=<non-aws ip address>
    leftid=<non-aws ip address>
    rightid=<aws elastic ip>
    right=%defaultroute
    authby=secret
    # load and initiate automatically
    auto=start

**Comment by marcinratajczak** [comment]
@eaparnell Did you solve this problem? I have a similar, it occurs on average once a week and only a restart of openswan helps

**Comment by eaparnell** [comment]
This was a while ago but I believe in my case it turned out to be a routing/firewall issue; I didn't experience the intermittent issues that you describe.
