### ISSUE TITLE
more subnet

### ISSUE THREAD

**Issue by wocale** [xelerance/Openswan#135]
I have two subnet ，but i can't use it like this.

leftsubnet=192.168.8.0/24 
leftsubnet=172.16.1.0/24

What should i change?

**Comment by mcr** [comment]
wocale <notifications@github.com> wrote:
 I have two subnet ，but i can't use it like this.

    > leftsubnet=192.168.8.0/24
    > leftsubnet=172.16.1.0/24

    > What should i change?

leftsubnets=192.168.8.0/24,172.16.1.0/24

This actually results on a cross-product of real conns being defined.
I.e. this is in some sense a macro.

"ipsec whack --status" would show you the result.

**Comment by wocale** [comment]
leftsubnets={192.168.8.0/24 172.16.1.0/24}
