### ISSUE TITLE
Openswan 2.6.45 issues?

### ISSUE THREAD

**Issue by KVasatko** [xelerance/Openswan#146]
Hi all,
I have problem with openswan 2.6.45. I tested it against 2.6.41 and I found same issues.
On Linux1 is openswan 2.6.45, on Linux2.6.41 is openswan 2.6.41 and are used X.509 certificates. If is openswan on Linux1 downgraded to 2.6.41, all works good.

1) Is established tunnel between Linux1 and Linux2. Is pinged from Linux1 to Linux2 side of tunnel and from Linux2 to Linux1 side of tunnel. During this time is restarted IPsec on Linux2. If tunnel is established, ping continue again but only for 8~20 seconds. After this time connectivity is lost. In system log are these messages: 

pluto[8643]: "ipsec1" #9: deleting state #9 (STATE_QUICK_R2)
pluto[8643]: | creating SPD to IPADDR-spi=00010000@IPADDR proto=255

This state is not addicted on cipher and hash algorithms.

2) ESP hash SHA 256 is not working good. Tunnel is established but is not possible to comunicate over him.

3) Is not possible to establish tunnel if is not set remote ip address on Linux1. In system log are these messages:

pluto[1040]: packet from IPADDR:500: Informational Exchange is for an unknown (expired?) SA with MSGID:0xfea2187c
pluto[1040]: packet from IPADDR:500: Informational Exchange is for an unknown (expired?) SA with MSGID:0x7c190e62
pluto[1040]: packet from IPADDR:500: received Vendor ID payload [Dead Peer Detection]
pluto[1040]: packet from IPADDR:500: initial Main Mode message received on IPADDR:500 but no connection has been authorized with policy=RSASIG

**Comment by letoams** [comment]
you need sha2-truncbug=yes possibly - not sure if openswan backported that from libreswan

**Comment by mcr** [comment]
sha2-truncbug, which AFAIK, works around an incorrect implementation of SHA2 in certain (now rather old) kernel versions in the 2.6.~30~ era, might affect things.
The problem you list in (1) is not related to SHA2, as far as I can tell.
The problem you list in (3) is also not related to SHA2, but looks like you haven't configured your policy correctly.  WIthout seeing your policy, I can't help further.

**Comment by letoams** [comment]
On Thu, 3 Dec 2015, Michael Richardson wrote:

> sha2-truncbug, which AFAIK, works around an incorrect implementation of SHA2 in certain (now rather old) kernel versions in the 2.6.~30~ era, might affect things.

"old kernels" is relative. for example, Android 6.x is affected by this.

Paul
