### ISSUE TITLE
ipsec tunnel doesn't up behined NAT

### ISSUE THREAD

**Issue by gaqi12** [xelerance/Openswan#160]
hi experts,
i setup a ipsec vpn tunnel, it was ok, but after i installed a NAT in between, the tunnel doesn't up again

error outputs:
packet from 172.16.0.164:500: initial Main Mode message received on 192.168.182.103:500 but no connection has been authorized with policy=PSK

please see the configruation

---
## <client side>

ipsec.secrets file:
192.168.177.1 192.168.182.103 : PSK "abc"

ipsec.conf file:

version 2.0    

config setup
        plutodebug=all
        plutostderrlog=/var/log/pluto.log
        protostack=netkey
        nat_traversal=yes
        virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/16
        oe=off

conn to-103
        authby=secret
        auto=add
        ike=3des-md5

```
    keyexchange=ike
    phase2=esp
    phase2alg=3des-md5
    compress=no
    pfs=yes
    type=tunnel
    left=192.168.177.1
    leftsubnet=192.168.10.0/24
    right=192.168.182.103
    rightsubnet=192.168.182.0/24
```

---
## <server side>

ipsec.secrets file:
192.168.182.103 192.168.177.1 : PSK "abc"

ipsec.conf file:

version 2.0    

config setup
        plutodebug=all
        plutostderrlog=/var/log/pluto.log
        protostack=netkey
        nat_traversal=yes
        virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/16
        oe=off

conn to-103
        authby=secret
        auto=add
        ike=3des-md5

```
    keyexchange=ike
    phase2=esp
    phase2alg=3des-md5
    compress=no
    pfs=yes
    type=tunnel
    left=192.168.182.103
    leftsubnet=192.168.182.0/24
    leftnexthop=192.168.182.95
    right=192.168.177.1
    rightsubnet=192.168.10.0/24
```

**Comment by chtomato** [comment]
Your problem is resolved？
I also encountered the same problem，
 the client device behined NAT,client connect the openswan server device is ok,but Network blocked。
