### ISSUE TITLE
Is 2.6.45 unstable?

### ISSUE THREAD

**Issue by steveleung** [xelerance/Openswan#179]
I found a statement which is come from the previous version of official openswan website: "If you have downloaded version 2.6.45 or 2.6.44, please revert to version 2.6.43.1, as 2.6.44 and 2.6.45 have been found to be unstable in certain environments. We are working on a fix."

So if I'm using 2.6.45, should I really need to stop using it and migrate to 2.6.43 or 2.6.46? Thank you.

**Comment by mcr** [comment]
Steve Leung <notifications@github.com> wrote:
    > I found a statement which is come from the previous version of
    > official openswan website: "If you have downloaded version 2.6.45 or
    > 2.6.44, please revert to version 2.6.43.1, as 2.6.44 and 2.6.45 have
    > been found to be unstable in certain environments. We are working on a
    > fix."

    > So if I'm using 2.6.45, should I really need to stop using it and
    > migrate to 2.6.43 or 2.6.46? Thank you.

If 2.6.45 works for you, you can continue to use it.

2.6.46 fixes a number of problems that showed up in 2.6.45 using IKEv2.
Plan/schedule an upgrade.


--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by steveleung** [comment]
So it should not be a problem if I'm still using IKEv1, thank you :)
