### ISSUE TITLE
make programs error

### ISSUE THREAD

**Issue by 7cigun** [xelerance/Openswan#183]
Hello.
I`m trying to compile openswan-2.6.46 on openwall-current. Kernel is 2.6.18.
I got error, when running "make programs".
Last messages is:

/usr/src/mybuild/openswan-2.6.46/lib/libcrypto/libsha2/sha2.c:517: undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: pluto: hidden symbol`__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: Bad value
collect2: ld returned 1 exit status
make[3]: **\* [pluto] Error 1
make[3]: Leaving directory `/usr/src/mybuild/openswan-2.6.46/OBJ.linux.i386/programs/pluto'
make[2]: *** [programs] Error 1
make[2]: Leaving directory`/usr/src/mybuild/openswan-2.6.46/OBJ.linux.i386/programs'
make[1]: **\* [programs] Error 1
make[1]: Leaving directory `/usr/src/mybuild/openswan-2.6.46/OBJ.linux.i386'
make: **\* [programs] Error 2

How to resolve this issue?

**Comment by shussain** [comment]
Is this issue occurring with 2.6.48?

**Comment by shussain** [comment]
Assuming it is no longer an active issue
