### ISSUE TITLE
compiling error 

### ISSUE THREAD

**Issue by AnatoliChe** [xelerance/Openswan#185]
CC connections.c
In file included from /usr/src/openswan-2.6.47/include/pluto/connections.h:127,
                 from /usr/src/openswan-2.6.47/programs/pluto/connections.c:51:
/usr/src/openswan-2.6.47/include/pluto/log.h:151: error: redefinition of typedef 'logfunc'
/usr/src/openswan-2.6.47/include/pluto/log.h:151: note: previous declaration of 'logfunc' was here
make[3]: *** [connections.o] Error 1

gcc version 4.4.5
[patch.txt](https://github.com/xelerance/Openswan/files/238520/patch.txt)
 (Debian 4.4.5-8)
kernel 3.2.78-debian

reason:
connections.h includes log.h
connections.c (and some other *.c) includes connections.h and log.h

dump patch:

diff -r openswan-2.6.47.orig/programs/pluto/ac.c openswan-2.6.47/programs/pluto/ac.c
47c47
< #include "log.h"
> /* #include "log.h" */
and do it for all 
[patch.txt](https://github.com/xelerance/Openswan/files/238520/patch.txt)
others

**Comment by shussain** [comment]
Thank you for your patch. We have fixed it using a slightly different way in commit 35b197d   

That commit is a development branch for the next release. 

If possible, can you confirm if the commit works for you? If not, we can fix it or pull in your patch.

**Comment by AnatoliChe** [comment]
Yeap, 35b197d works perfectly.
Thanks a lot.
