### ISSUE TITLE
Openswan 2.6.32 VPN with Windows Server 2012 R2 initiation problem

### ISSUE THREAD

**Issue by lokkoo** [xelerance/Openswan#186]
Hello All,

Thank you for reading.

I have an IPsec VPN connection setup between an RHEL 6.5 using openswan 2.6.32 (I believe this should be the latest version available for RHEL 6.5) with a Windows Server 2012 R2 using Windows Firewall VPN. 
When there are no existing VPN connections, pinging from RHEL to Windows will not work no matter how long I wait.

But whenever I started pinging from Windows to RHEL, the VPN connection will establish immediately and ping will then now work both ways. This will work until the connection time out or until I restart the openswan service.

I found an error in /var/log/secure: Apr 27 19:11:38 hostname pluto[9482]: packet from 192.168.1.4:500: missing payload(s) (ISAKMP_NEXT_v2SA+ISAKMP_NEXT_v2KE+ISAKMP_NEXT_v2Ni). Message dropped.

Grateful if anyone could shed some light on the matter.

Thanks and Regards,
Lok

**Comment by letoams** [comment]
Try the version from rhel-6.7 which is the latest. I think it is 2.6.32-38.

Rhel-6.8 will obsolete openswan for libreswan. You can grab the prerelease from rhel7-extras

Paul (rhel IPSec maintainer)

Sent from my iPhone

**Comment by lokkoo** [comment]
Hello Paul,

Thank you for your reply.
I have been searching RHEL Customer Portal and the latest I could find is 2.6.32-37 (which is the one I am using).
Besides, would I be able to use openswan 2.6.32-38 if my RHEL is only RHEL 6.5 instead of 6.7?

Thank you again for your help.

Regards,
Lok

**Comment by letoams** [comment]
On Tue, 3 May 2016, lokkoo wrote:

> Thank you for your reply.
> I have been searching RHEL Customer Portal and the latest I could find is 2.6.32-37 (which
> is the one I am using).
> Besides, would I be able to use openswan 2.6.32-38 if my RHEL is only RHEL 6.5 instead of
> 6.7?

Oh you are right. We never released -38 as we instead decided to move
libreswan into rhel6. And the only change to -37 relates to a fix to OCSP.

Paul
