### ISSUE TITLE
can't get passed this "pending Phase 2 for "myPC" replacing #0" any pointer

### ISSUE THREAD

**Issue by sekayasin** [xelerance/Openswan#190]
hello there, 

here are my ipsec auto --status

000 "myPC": 178.62.5.27/32===178.62.5.27<178.62.5.27>---178.62.0.1...41.202.229.3<41.202.229.3>===172.19.21.0/24; prospective erouted; eroute owner: #0
000 "myPC":     myip=178.62.5.27; hisip=unset;
000 "myPC":   ike_life: 3600s; ipsec_life: 28800s; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 0
000 "myPC":   policy: PSK+ENCRYPT+TUNNEL+UP+IKEv2ALLOW+SAREFTRACK+lKOD+rKOD; prio: 32,24; interface: eth0;
000 "myPC":   newest ISAKMP SA: #0; newest IPsec SA: #0;
000 "myPC":   ESP algorithms wanted: AES(12)_128-SHA1(2)_000; flags=-strict
000 "myPC":   ESP algorithms loaded: AES(12)_128-SHA1(2)_160
000
000 #20: "myPC":500 STATE_MAIN_I1 (sent MI1, expecting MR1); EVENT_RETRANSMIT in 4s; nodpd; idle; import:admin initiate
000 #20: pending Phase 2 for "myPC" replacing #0

**Comment by shussain** [comment]
Is this issue still occurring?  Can you confirm it still occurs in the latest version of Openswan (2.6.49).

If the issue still occurs, can you please provide your  ipsec configuration (/etc/ipsec.conf)
