### ISSUE TITLE
STATE_QUICK_I1: initiate, any pointer on this 

### ISSUE THREAD

**Issue by sekayasin** [xelerance/Openswan#191]
ipsec auto --up myConn

104 "myConn" #281: STATE_MAIN_I1: initiate
003 "myConn" #281: received Vendor ID payload [draft-ietf-ipsec-nat-t-ike-02_n] method set to=106
003 "myConn" #281: ignoring Vendor ID payload [FRAGMENTATION c0000000]
106 "myConn" #281: STATE_MAIN_I2: sent MI2, expecting MR2
003 "myConn" #281: received Vendor ID payload [Cisco-Unity]
003 "myConn" #281: received Vendor ID payload [XAUTH]
003 "myConn" #281: ignoring unknown Vendor ID payload [ad631e9af00364684d82c285fd11be28]
003 "myConn" #281: ignoring Vendor ID payload [Cisco VPN 3000 Series]
003 "myConn" #281: NAT-Traversal: Result using draft-ietf-ipsec-nat-t-ike-02/03: no NAT detected
108 "myConn" #281: STATE_MAIN_I3: sent MI3, expecting MR3
003 "myConn" #281: received Vendor ID payload [Dead Peer Detection]
004 "myConn" #281: STATE_MAIN_I4: ISAKMP SA established {auth=OAKLEY_PRESHARED_KEY cipher=aes_128 prf=oakley_sha group=modp1024}
117 "myConn" #282: STATE_QUICK_I1: initiate
010 "myConn" #282: STATE_QUICK_I1: retransmission; will wait 20s for response
010 "myConn" #282: STATE_QUICK_I1: retransmission; will wait 40s for response

and here is ipsec auto --status
000 "myConn":   ike_life: 3600s; ipsec_life: 28800s; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 0; nat_keepalive: yes
000 "myConn":   policy: PSK+ENCRYPT+TUNNEL+UP+IKEv2ALLOW+SAREFTRACK+lKOD+rKOD; prio: 32,32; interface: eth0;
000 "myConn":   newest ISAKMP SA: #0; newest IPsec SA: #0;
000 "myConn":   IKE algorithms wanted: AES_CBC(7)_128-SHA1(2)_000-MODP1536(5), AES_CBC(7)_128-SHA1(2)_000-MODP1024(2)
000 "myConn":   IKE algorithms found:  AES_CBC(7)_128-SHA1(2)_160-MODP1536(5), AES_CBC(7)_128-SHA1(2)_160-MODP1024(2)
000 "myConn":   ESP algorithms wanted: AES(12)_128-SHA1(2)_000
000 "myConn":   ESP algorithms loaded: AES(12)_128-SHA1(2)_160
000
000 #286: "myConn":500 STATE_QUICK_I1 (sent QI1, expecting QR1); EVENT_RETRANSMIT in 36s; lastdpd=-1s(seq in:0 out:0); idle; import:admin initiate
000 #288: "myConn":500 STATE_QUICK_I1 (sent QI1, expecting QR1); EVENT_RETRANSMIT in 17s; lastdpd=-1s(seq in:0 out:0); idle; import:admin initiate
000

**Comment by shussain** [comment]
What version of Openswan are you using? 

Are the logs showing any error?

**Comment by sekayasin** [comment]
[root@li447-43 ~]# ipsec --version
Linux Openswan U2.6.32/K4.5.0-x86_64-linode65 (netkey)
See `ipsec --copyright' for copyright information.
[root@li447-43 ~]# 

root@li447-43 ~]# ipsec verify
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Checking your system to see if IPsec got installed and started correctly:
Version check and ipsec on-path                             	[OK]
Linux Openswan U2.6.32/K4.5.0-x86_64-linode65 (netkey)
Checking for IPsec support in kernel                        	[OK]
 SAref kernel support                                       	[N/A]
 NETKEY:  Testing for disabled ICMP send_redirects          	[OK]
NETKEY detected, testing for disabled ICMP accept_redirects 	[OK]
Hardware RNG detected, testing if used properly             	[OK]
Checking that pluto is running                              	[OK]
 Pluto listening for IKE on udp 500                         	[OK]
 Pluto listening for NAT-T on udp 4500                      	[OK]
Two or more interfaces found, checking IP forwarding        	[OK]
Checking NAT and MASQUERADEing                              	[OK]
Checking for 'ip' command                                   	[OK]
Checking /bin/sh is not /bin/dash                           	[OK]
Checking for 'iptables' command                             	[OK]
Opportunistic Encryption Support                            	[DISABLED]
[root@li447-43 ~]#

**Comment by sekayasin** [comment]
i finally got this working!!! one the other side, the third party had enabled pfs at their side, yet at my side i had disabled pfs, (pfs=no).. the third party have a cisco asa fw!, after disabling pfs, everything worked like charm, SA were established.. and would ping their LAN nodes behind the ASA fw!!
