### ISSUE TITLE
ipsec verify error, kernel doesn't support

### ISSUE THREAD

**Issue by wxlcat** [xelerance/Openswan#193]
I am trying to compile openswan in kernel 2.6.32 using command: "make programs install". After that, "ipsec vertify" shows kernel doesn't support, what should i do ? Thanks!!

environment: bandwangonhost vps (OpenVZ), debian kernel 2.6.32

Detail：
Checking for IPsec support in kernel                    [FAILED]

The ipsec service should be started before running 'ipsec verify'

Hardware random device check                            [N/A]
Checking rp_filter                                      [ENABLED]
 /proc/sys/net/ipv4/conf/lo/rp_filter                   [ENABLED]
 /proc/sys/net/ipv4/conf/venet0/rp_filter               [ENABLED]
 /proc/sys/net/ipv4/conf/ipsec0/rp_filter               [ENABLED]
Checking that pluto is running                          [FAILED]
Checking NAT and MASQUERADEing                          [TEST INCOMPLETE]
Checking 'ip' command                                   [OK]
Checking 'iptables' command                             [OK]

**Comment by simondeziel** [comment]
The OpenVZ kernel doesn't allow you to use Openswan in a VE. It only let
you run in the host context.
