### ISSUE TITLE
v2.6.48 do not sent dpd or liveness packet when working on ikev2

### ISSUE THREAD

**Issue by 1309578252** [xelerance/Openswan#195]
1. if "ikev2=insist", our Openswan do not send any dpd or liveness packets such as ISAKMP_v2_INFORMATIONAL to peer.
2. if peer site is only an responder, such as strongswan or cisco CSR1000, after tunnel established, strongswan or CSR1000 will send  ISAKMP_v2_INFORMATIONAL to Openswan to do liveness check with message ID=0,
   our Openswan do not response this message, it will cause peer side CSR1000 delete established VPN route and VPN communication failed.
3. if peer site(strongswan) is only an initiator and our openswan set "auto=add" to act as a responder, after tunnel was established, the first liveness check message ID from stongswan is 2, and i think the value was correct, 
   our Openswan could response it correctly, and liveness check works fine.

**Comment by letoams** [comment]
In the libreswan fork we fixed a number of msgid bugs that are present in openswan. In informational exchange but also in ike_auth. The old rhel openswan package contains some of these patches (but now rhel6 also moved to libreswan so that tree is no longer maintained ).
