### ISSUE TITLE
does v2.6.48 support child_sa? how does child_sa work?

### ISSUE THREAD

**Issue by 1309578252** [xelerance/Openswan#196]
if two tunnels share the same WAN, in strongswan, the second tunnel will ask to create child_sa and mostly the message id is 2, but openswan2.6.48 response a message with v2N_INVALID_MESSAGE_ID. 
how does child_sa work on openswan?
i think there are some critical bugs about message id on openswan2.6.48.
and child sa functions was missing

**Comment by letoams** [comment]
On Thu, 16 Jun 2016, 1309578252 wrote:

> if two tunnels share the same WAN, in strongswan, the second tunnel will ask
> to create child_sa and mostly the message id is 2, but openswan2.6.48
> response a message with v2N_INVALID_MESSAGE_ID.
> how does child_sa work on openswan?
> i think there are some critical bugs about message id on openswan2.6.48.
> and child sa functions was missing

openswan does not implement the CREATE_CHILD_SA exchange.

Paul

**Comment by shussain** [comment]
Creating CHILD_SA is currently being actively developed. We are planning on having it as part of the next Openswan release (2.6.49)

**Comment by 1309578252** [comment]
thanks， could you tell me when 2.6.49 will release? also expect the communication between Cisco CSR1000 on IKEv2

**Comment by mcr** [comment]
I would say, in about two weeks.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by 1309578252** [comment]
![openswan_csr1000_ikev2 packets](https://cloud.githubusercontent.com/assets/16505069/16251568/aa4a59ec-3859-11e6-9fd2-a902c4e17112.png)
change ".png" to ".zip", then unzip it, we could get the packets about Openswan2.6.48 IKEv2 behavior against CSR1000 and Strongswan

**Comment by 1309578252** [comment]
There is a fatal DPD bug on IKEv2, Openswan V2.6.48 do not response CSR1000's  or Strongswan's DPD packets, this bug makes Openswan could not work against CSR1000 or Strongswan, could this bug fixed in 2.6.49 too?

**Comment by shussain** [comment]
Regarding the DPD bug, do you have any logs or error available?

Due to our focus on child SA, we will not be able to fix the DPD bug for the 2.6.49 release but we can certainly look into it afterwards and keep you up to date on our status regarding that.

**Comment by 1309578252** [comment]
Jun 15 16:40:50 pluto[10398]: | next event EVENT_PENDING_DDNS in 0 seconds
Jun 15 16:40:50 pluto[10398]: | *time to handle event
Jun 15 16:40:50 pluto[10398]: | at 2016-06-15 16:40:50 handling event EVENT_PENDING_DDNS
Jun 15 16:40:50 pluto[10398]: | event after this is EVENT_PENDING_PHASE2 in 60 seconds
Jun 15 16:40:50 pluto[10398]: | inserting event EVENT_PENDING_DDNS, timeout in 60 seconds (head of queue)
Jun 15 16:40:50 pluto[10398]: | next event EVENT_PENDING_DDNS in 60 seconds
Jun 15 16:41:50 pluto[10398]: | 
Jun 15 16:41:50 pluto[10398]: | next event EVENT_PENDING_DDNS in 0 seconds
Jun 15 16:41:50 pluto[10398]: | *time to handle event
Jun 15 16:41:50 pluto[10398]: | at 2016-06-15 16:41:50 handling event EVENT_PENDING_DDNS
Jun 15 16:41:50 pluto[10398]: | event after this is EVENT_PENDING_PHASE2 in 0 seconds
Jun 15 16:41:50 pluto[10398]: | inserting event EVENT_PENDING_DDNS, timeout in 60 seconds 
Jun 15 16:41:50 pluto[10398]: | event added after event EVENT_PENDING_PHASE2
Jun 15 16:41:50 pluto[10398]: | at 2016-06-15 16:41:50 handling event EVENT_PENDING_PHASE2
Jun 15 16:41:50 pluto[10398]: | event after this is EVENT_PENDING_DDNS in 60 seconds
Jun 15 16:41:50 pluto[10398]: | inserting event EVENT_PENDING_PHASE2, timeout in 120 seconds 
Jun 15 16:41:50 pluto[10398]: | event added after event EVENT_PENDING_DDNS
Jun 15 16:41:50 pluto[10398]: | pending review: connection "loopback" being checked
Jun 15 16:41:50 pluto[10398]: | checking connection "loopback" for stuck phase 2s (1466008798+ 3*0) <= 1466008910
Jun 15 16:41:50 pluto[10398]: | pending review: connection "loopback" not time for review
Jun 15 16:41:50 pluto[10398]: | pending review: connection "data2" being checked
Jun 15 16:41:50 pluto[10398]: | checking connection "data2" for stuck phase 2s (1466008801+ 3*0) <= 1466008910
Jun 15 16:41:50 pluto[10398]: | checking connection "data2" for stuck phase 2s (1466008797+ 3*0) <= 1466008910
Jun 15 16:41:50 pluto[10398]: | checking connection "data2" for stuck phase 2s (1466008796+ 3*0) <= 1466008910
Jun 15 16:41:50 pluto[10398]: | pending review: connection "data2" not time for review
Jun 15 16:41:50 pluto[10398]: | pending review: connection "data1" being checked
Jun 15 16:41:50 pluto[10398]: |   no additional DNS answers,  not re-attempting
Jun 15 16:41:50 pluto[10398]: pending Quick Mode with 192.168.10.244 "data1" took too long -- replacing phase 1
Jun 15 16:41:50 pluto[10398]: | next event EVENT_PENDING_DDNS in 60 seconds
Jun 15 16:42:50 pluto[10398]: | 
Jun 15 16:42:50 pluto[10398]: | next event EVENT_PENDING_DDNS in 0 seconds
Jun 15 16:42:50 pluto[10398]: | *time to handle event
Jun 15 16:42:50 pluto[10398]: | at 2016-06-15 16:42:50 handling event EVENT_PENDING_DDNS
Jun 15 16:42:50 pluto[10398]: | event after this is EVENT_PENDING_PHASE2 in 60 seconds
Jun 15 16:42:50 pluto[10398]: | inserting event EVENT_PENDING_DDNS, timeout in 60 seconds (head of queue)
Jun 15 16:42:50 pluto[10398]: | next event EVENT_PENDING_DDNS in 60 seconds
Jun 15 16:43:50 pluto[10398]: | 
Jun 15 16:43:50 pluto[10398]: | next event EVENT_PENDING_DDNS in 0 seconds
Jun 15 16:43:50 pluto[10398]: | *time to handle event
Jun 15 16:43:50 pluto[10398]: | at 2016-06-15 16:43:50 handling event EVENT_PENDING_DDNS
Jun 15 16:43:50 pluto[10398]: | event after this is EVENT_PENDING_PHASE2 in 0 seconds
Jun 15 16:43:50 pluto[10398]: | inserting event EVENT_PENDING_DDNS, timeout in 60 seconds 
Jun 15 16:43:50 pluto[10398]: | event added after event EVENT_PENDING_PHASE2
Jun 15 16:43:50 pluto[10398]: | at 2016-06-15 16:43:50 handling event EVENT_PENDING_PHASE2
Jun 15 16:43:50 pluto[10398]: | event after this is EVENT_PENDING_DDNS in 60 seconds
Jun 15 16:43:50 pluto[10398]: | inserting event EVENT_PENDING_PHASE2, timeout in 120 seconds 
Jun 15 16:43:50 pluto[10398]: | event added after event EVENT_PENDING_DDNS
Jun 15 16:43:50 pluto[10398]: | pending review: connection "loopback" being checked
Jun 15 16:43:50 pluto[10398]: | checking connection "loopback" for stuck phase 2s (1466008798+ 3*0) <= 1466009030
Jun 15 16:43:50 pluto[10398]: | pending review: connection "loopback" not time for review
Jun 15 16:43:50 pluto[10398]: | pending review: connection "data2" being checked
Jun 15 16:43:50 pluto[10398]: | checking connection "data2" for stuck phase 2s (1466008801+ 3*0) <= 1466009030
Jun 15 16:43:50 pluto[10398]: | checking connection "data2" for stuck phase 2s (1466008797+ 3*0) <= 1466009030
Jun 15 16:43:50 pluto[10398]: | checking connection "data2" for stuck phase 2s (1466008796+ 3*0) <= 1466009030
Jun 15 16:43:50 pluto[10398]: | pending review: connection "data2" not time for review
Jun 15 16:43:50 pluto[10398]: | pending review: connection "data1" being checked
Jun 15 16:43:50 pluto[10398]: |   no additional DNS answers,  not re-attempting
Jun 15 16:43:50 pluto[10398]: pending Quick Mode with 192.168.10.244 "data1" took too long -- replacing phase 1
Jun 15 16:43:50 pluto[10398]: | next event EVENT_PENDING_DDNS in 60 seconds
Jun 15 16:44:02 pluto[10398]: | 
Jun 15 16:44:02 pluto[10398]: | *received 76 bytes from 192.168.10.244:500 on eth0.2 (port=500) at 2016-06-15 16:44:02
Jun 15 16:44:02 pluto[10398]: |   35 11 64 d0  27 40 a0 e0  60 db 7c 5d  7d 0c 11 4c
Jun 15 16:44:02 pluto[10398]: |   2e 20 25 00  00 00 00 00  00 00 00 4c  2a 00 00 30
Jun 15 16:44:02 pluto[10398]: |   2d cf 3c 33  e3 86 e3 a4  66 f1 82 5e  ef b4 e1 52
Jun 15 16:44:02 pluto[10398]: |   88 5f 05 13  48 c6 49 79  47 78 09 12  a9 d1 0c 4b
Jun 15 16:44:02 pluto[10398]: |   64 f0 19 b4  5d 5e 4b ec  48 be 0e 17
Jun 15 16:44:02 pluto[10398]: | **parse ISAKMP Message:
Jun 15 16:44:02 pluto[10398]: |    initiator cookie:
Jun 15 16:44:02 pluto[10398]: |   35 11 64 d0  27 40 a0 e0
Jun 15 16:44:02 pluto[10398]: |    responder cookie:
Jun 15 16:44:02 pluto[10398]: |   60 db 7c 5d  7d 0c 11 4c
Jun 15 16:44:02 pluto[10398]: |    next payload type: ISAKMP_NEXT_v2E
Jun 15 16:44:02 pluto[10398]: |    ISAKMP version: IKEv2 version 2.0 (rfc4306/rfc5996)
Jun 15 16:44:02 pluto[10398]: |    exchange type: ISAKMP_v2_INFORMATIONAL
Jun 15 16:44:02 pluto[10398]: |    flags: none
Jun 15 16:44:02 pluto[10398]: |    message ID:  00 00 00 00
Jun 15 16:44:02 pluto[10398]: |    length: 76
Jun 15 16:44:02 pluto[10398]: |  processing version=2.0 packet with exchange type=ISAKMP_v2_INFORMATIONAL (37), msgid: 00000000
Jun 15 16:44:02 pluto[10398]: | I am IKE SA Initiator
Jun 15 16:44:02 pluto[10398]: | ICOOKIE:  35 11 64 d0  27 40 a0 e0
Jun 15 16:44:02 pluto[10398]: | RCOOKIE:  60 db 7c 5d  7d 0c 11 4c
Jun 15 16:44:02 pluto[10398]: | state hash entry 7
Jun 15 16:44:02 pluto[10398]: | v2 peer and cookies match on #4
Jun 15 16:44:02 pluto[10398]: | v2 state object #4 (data2) found, in STATE_PARENT_I3
Jun 15 16:44:02 pluto[10398]: | responding peer retransmitted msgid 0 (retransmission count: 1)
Jun 15 16:44:02 pluto[10398]: | * processed 0 messages from cryptographic helpers 
Jun 15 16:44:03 pluto[10398]: | next event EVENT_PENDING_DDNS in 47 seconds
Jun 15 16:44:03 pluto[10398]: | next event EVENT_PENDING_DDNS in 47 seconds

**Comment by 1309578252** [comment]
Jun 15 16:41:50 pluto[10398]: pending Quick Mode with 192.168.10.244 "data1" took too long -- replacing phase 1

Jun 15 16:44:02 pluto[10398]: |  processing version=2.0 packet with exchange type=ISAKMP_v2_INFORMATIONAL (37), msgid: 00000000

**Comment by shussain** [comment]
Thank you for the logs.

We have created a branch for [2.6.49](https://github.com/xelerance/Openswan/tree/2.6.49dev) which has the child SA support. There is also a  [tag](https://github.com/xelerance/Openswan/releases/tag/v2.6.49dev) that you can use.

When you get a chance, could you please test it using your setup and give us any feedback you might have.

**Comment by tylerhen** [comment]
in trying to install 2.6.49, it creates lots of errors.  I read the readme and I have all the requirements.

**Comment by shussain** [comment]
If I understand you correctly, you are having issues with building the package? What command are you using to build (e.g. make programs)? On what system (e.g. Ubuntu 14.04 x86_64)?

**Comment by shussain** [comment]
@tylerhen is your issue still occurring? If it is, please feel free to open a new issue ticket.

2.6.59 has been released, therefore closing this ticket.
