### ISSUE TITLE
Where can I download the user manual of openswan.

### ISSUE THREAD

**Issue by wangwzc** [xelerance/Openswan#200]
Where can I download the user manual of openswan.

**Comment by wangwzc** [comment]
I want to conifgure the openswan, e.g. to add some rule for IPsec.

**Comment by wangwzc** [comment]
Does it support to use command line to add / remove connection?
And how to configure .

**Comment by shussain** [comment]
Yes, Openswan can add / remove connection with:
    [sudo] ipsec auto --up [connection_name]

In regards to how to configuring, here are some  [example connections:](https://github.com/xelerance/Openswan/tree/master/programs/examples). In addition, when you do an installation, the /etc/ipsec.d/examples has the above as example configurations.

**Comment by wangwzc** [comment]
This command is used to start up a connection.
 
Is the parameter of the connection can be configured via the command line but not edit the /etc/ipsec.conf file.

**Comment by shussain** [comment]
We recommend using ipsec.conf to configure your connections.

However, if you really, really wish to use the command line to add /remove connections, you can do so via whack (sudo ipsec whack --help; man ipsec_pluto)

**Comment by wangwzc** [comment]
Editing ipsec.conf file is convenient for manually operated.
But i want to configure connection by program, it a bit inconvenient . e.g. if I want to edit a parameter of one connection. The program need to parser the /etc/ipsec.conf file, and locate to the corresponding connection, then edit the parameter, and it also need to calculate the paraemter length, otherwise, it maybe overate the subsequent content.

**Comment by shussain** [comment]
If I understand your needs correctly, you can address it by having the ipsec.conf read all configurations in _/etc/ipsec.d/_  In that directory, you can have one file for each connection.

So your /etc/ipsec.conf woudl be:

```
version 2

config setup
  nat_traversal=yes
  virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:25.0.0.0/8,%v6:fd00::/8,%v6:fe80::/10,%v4:!172.24.24.0/22,%v4:!172.31.0.0/16,%v4:!192.168.88.0/24,%v4:!10.153.140.0/24,%v4:!192.168.24.0/24
  protostack=netkey
  #plutodebug="control dpd"

include /etc/ipsec.d/*.conf

```

And in /etc/ipsec.d, you could have multiple different files which contain something like:
```
conn connection1
  right=<ip address>
  rightid=@rigthtidvalue
  left=%any
  leftid=@leftidvalue
  authby=secret
  auto=add

```

**Comment by shussain** [comment]
Hi. Is your issue resolved? Can I go ahead and close this ticket?
