### ISSUE TITLE
OpenSwan >= 2.6.46 + rsasig = INVALID_KEY_INFORMATION

### ISSUE THREAD

**Issue by AnatoliChe** [xelerance/Openswan#206]
Hi there!
First of all with 2.6.43 (and lower version) everything is ok

`ipsec auto --up dpt
104 "dpt" #3: STATE_MAIN_I1: initiate
003 "dpt" #3: received Vendor ID payload [Openswan (this version) 2.6.41 ]
003 "dpt" #3: received Vendor ID payload [Dead Peer Detection]
106 "dpt" #3: STATE_MAIN_I2: sent MI2, expecting MR2
108 "dpt" #3: STATE_MAIN_I3: sent MI3, expecting MR3
003 "dpt" #3: received Vendor ID payload [CAN-IKEv2]
004 "dpt" #3: STATE_MAIN_I4: ISAKMP SA established {auth=OAKLEY_RSA_SIG cipher=aes_128 prf=OAKLEY_SHA2_256 group=modp1536}
117 "dpt" #4: STATE_QUICK_I1: initiate
004 "dpt" #4: STATE_QUICK_I2: sent QI2, IPsec SA established transport mode {ESP=>0x545a4c1b <0x8796cde7 xfrm=AES_256-HMAC_SHA2_256 NATOA=none NATD=none DPD=enabled}
`

ok

`ipsec auto listall
ipsec auto: warning: obsolete command syntax used
000  
000 List of Public Keys:
000  
000 Sep 10 22:27:11 2016, 4096 RSA Key AQN1dXSAE (no private key), until --- -- --:--:-- ---- ok (expires never)
000        ID_FQDN '@venera'
000 Sep 10 22:27:11 2016, 4096 RSA Key AQOY5v+Zt (has private key), until --- -- --:--:-- ---- ok (expires never)
000        ID_FQDN '@mars'
000 List of Pre-shared secrets (from /etc/ipsec.secrets)
000     1: RSA (none) (none)
`

ok. We can see our private key.

Now install OpenSwan 2.6.46 or higher (2.4.49)

`ipsec auto --up dpt
002 "dpt" #2: initiating Main Mode
105 "dpt" #2: STATE_MAIN_I1: initiate
003 "dpt" #2: ignoring unknown Vendor ID payload [4f535773786c6a4640545359]
003 "dpt" #2: received Vendor ID payload [Dead Peer Detection]
002 "dpt" #2: transition from state STATE_MAIN_I1 to state STATE_MAIN_I2
107 "dpt" #2: STATE_MAIN_I2: sent MI2, expecting MR2
002 "dpt" #2: transition from state STATE_MAIN_I2 to state STATE_MAIN_I3
109 "dpt" #2: STATE_MAIN_I3: sent MI3, expecting MR3
003 "dpt" #2: received Vendor ID payload [CAN-IKEv2]
002 "dpt" #2: Main mode peer ID is ID_FQDN: '@venera'
003 "dpt" #2: Signature check (on @venera) failed: tried *AQN1dXSAE *AQOY5v+Zt keys but none worked.
217 "dpt" #2: STATE_MAIN_I3: INVALID_KEY_INFORMATION
002 "dpt" #2: sending encrypted notification INVALID_KEY_INFORMATION to 192.168.44.1:500
`

`ipsec auto listall
ipsec auto: warning: obsolete command syntax used
000  
000 List of Public Keys:
000  
000 Sep 10 22:31:44 2016, 4096 RSA Key AQN1dXSAE (no private key), until --- -- --:--:-- ---- ok (expires never)
000        ID_FQDN '@venera'
000 Sep 10 22:31:44 2016, 4096 RSA Key AQOY5v+Zt (no private key), until --- -- --:--:-- ---- ok (expires never)
000        ID_FQDN '@mars'
000 List of Pre-shared secrets (from /etc/ipsec.secrets)
000     1: RSA (none) (none)
`

We cannot see our priv key
but:

`/usr/local/libexec/ipsec/secrets 
002 forgetting secrets
002 loading secrets from "/etc/ipsec.secrets"
002 loaded private key for keyid: PPK_RSA:AQOY5v+Zt
`
it's loaded, check 

`/usr/local/libexec/ipsec/whack --listall    
000  
000 List of Public Keys:
000  
000 Sep 10 22:31:44 2016, 4096 RSA Key AQN1dXSAE (no private key), until --- -- --:--:-- ---- ok (expires never)
000        ID_FQDN '@venera'
000 Sep 10 22:31:44 2016, 4096 RSA Key AQOY5v+Zt (no private key), until --- -- --:--:-- ---- ok (expires never)
000        ID_FQDN '@mars'
000 List of Pre-shared secrets (from /etc/ipsec.secrets)
000     1: RSA (none) (none)
`
nop... no key

**Comment by shussain** [comment]
Hello. Thank you for opening this issue ticket

We are aware of a regression with RSA Signatures of keysize of 4032 bits or longer failing. We are working on a solution and are planning on having it as part of 2.6.50 release. Would you like to know when we merge the fix into our development branch or when we create release candidate tags?

**Comment by AnatoliChe** [comment]
As you prefer.
I have set up a virt enviroment and ready to test patch/dev branch/rc in different configurations, with different leight keys :-)
Thanks for the answer.

**Comment by mcr** [comment]
AnatoliChe <notifications@github.com> wrote:
    > As you prefer.
    > I have set up a virt enviroment and ready to test patch/dev branch/rc in
    > different configurations, with different leight keys :-)
    > Thanks for the answer.

You will find that tests/unit/libopenswan/lo02-verifysigs loads a series of
keys and verify that the signatures made with them can be validated by the
public key.  If you want to verify longer keys, please go ahead...

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by shussain** [comment]
The RSA key size fix is in the [2.6.50dev branch](https://github.com/xelerance/Openswan/tree/2.6.50dev).

**Comment by AnatoliChe** [comment]
2.6.50dev is one big segfault ( Sorry
ipsec auto -add dpt
and catch a ton of segfaults. I don't know haw to manage and debug it.
2.6.43.1 works like a charm

**Comment by shussain** [comment]
Are you using IKEv1? We had encountered problems with IKEv1 and a fix is in the 2.6.50dev branch.

If you are using IKEv2 or if segfaults are still occurring, can you please provide your ipsec configuration

**Comment by AnatoliChe** [comment]
Yes it's IKEv1 and 2.6.50~dev4-0xelerance1 git from 2017-01-30
conn %default
        keyingtries=0
        disablearrivalcheck=no
        authby=rsasig
        keyexchange=ike
        keylife=20m
        pfs=yes
        rekeymargin=5m
        rekeyfuzz=50%
        ike=aes-sha2_256
        esp=aes-sha2_256

working

**Comment by shussain** [comment]
Sorry, are you saying it all working? 

If not, just to clarify have you tried the 2.6.50dev branch with the lastest code (it would be v2.6.50dev6)

**Comment by AnatoliChe** [comment]
Yeap, it's working.
v2.6.50dev6
# ipsec auto --up testconn
002 "testconn" #3: initiating Main Mode
104 "testconn" #3: STATE_MAIN_I1: initiate
003 "testconn" #3: received Vendor ID payload [Openswan (this version) 2.6.43 ]
003 "testconn" #3: received Vendor ID payload [Dead Peer Detection]
002 "testconn" #3: transition from state STATE_MAIN_I1 to state STATE_MAIN_I2
106 "testconn" #3: STATE_MAIN_I2: sent MI2, expecting MR2
002 "testconn" #3: transition from state STATE_MAIN_I2 to state STATE_MAIN_I3
108 "testconn" #3: STATE_MAIN_I3: sent MI3, expecting MR3
003 "testconn" #3: received Vendor ID payload [CAN-IKEv2]
002 "testconn" #3: Main mode peer ID is ID_FQDN: '@venera'
002 "testconn" #3: transition from state STATE_MAIN_I3 to state STATE_MAIN_I4
004 "testconn" #3: STATE_MAIN_I4: ISAKMP SA established {auth=OAKLEY_RSA_SIG cipher=aes_128 prf=OAKLEY_SHA2_256 group=modp1536}
002 "testconn" #3: Dead Peer Detection (RFC 3706): enabled
002 "testconn" #4: initiating Quick Mode RSASIG+ENCRYPT+PFS+UP+IKEv2ALLOW+SAREFTRACK {using isakmp#3 msgid:fb73dd54 proposal=AES(12)_128-SHA2_256(5)_256 pfsgroup=OAKLEY_GROUP
117 "testconn" #4: STATE_QUICK_I1: initiate
002 "testconn" #4: Dead Peer Detection (RFC 3706): enabled
002 "testconn" #4: transition from state STATE_QUICK_I1 to state STATE_QUICK_I2
004 "testconn" #4: STATE_QUICK_I2: sent QI2, IPsec SA established transport mode {ESP=>0xf08819da <0xdd2bec56 xfrm=AES_256-HMAC_SHA2_256 NATOA=none NATD=none DPD=enabled}

#ipsec auto --status


000 "testconn": 192.168.55.17<192.168.55.17>[@mars]---192.168.55.5...192.168.55.5---192.168.55.1<192.168.55.1>[@venera]; erouted; eroute owner: #2
000 "testconn":     myip=unset; hisip=unset; myup=/ramdisk/sbin/ipsec.updown;
000 "testconn":   ike_life: 3600s; ipsec_life: 1200s; rekey_margin: 300s; rekey_fuzz: 50%; keyingtries: 0
000 "testconn":   policy: RSASIG+ENCRYPT+PFS+UP+IKEv2ALLOW+SAREFTRACK; prio: 32,32; interface: eth1;
000 "testconn":   dpd: action:restart; delay:30; timeout:120;
000 "testconn":   newest ISAKMP SA: #1; newest IPsec SA: #2;
000 "testconn":   IKE algorithms wanted: AES_CBC(7)_000-SHA2_256(4)_000-MODP1536(5), AES_CBC(7)_000-SHA2_256(4)_000-MODP1024(2); flags=-strict
000 "testconn":   IKE algorithms found:  AES_CBC(7)_128-SHA2_256(4)_256-MODP1536(5)AES_CBC(7)_128-SHA2_256(4)_256-MODP1024(2)
000 "testconn":   IKE algorithm newest: AES_CBC_128-SHA2_256-MODP1536
000 "testconn":   ESP algorithms wanted: AES(12)_000-SHA2_256(5)_000; flags=-strict
000 "testconn":   ESP algorithms loaded: AES(12)_128-SHA2_256(5)_256
000 "testconn":   ESP algorithm newest: AES_256-HMAC_SHA2_256; pfsgroup=<Phase1>
000  
000 #2: "testconn":500 STATE_QUICK_I2 (sent QI2, IPsec SA established); EVENT_SA_REPLACE in 770s; newest IPSEC; eroute owner; isakmp#1; idle; import:admin initiate
000 #2: "testconn" esp.1d69e27a@192.168.55.1 esp.7f2fcb8b@192.168.55.17 ref=0 refhim=4294901761
000 #1: "testconn":500 STATE_MAIN_I4 (ISAKMP SA established); EVENT_SA_REPLACE in 3244s; newest ISAKMP; lastdpd=6s(seq in:3478 out:0); idle; import:admin initiate

**Comment by AnatoliChe** [comment]
Yes, it works. Let's close.

~# ipsec auto --up testconn
002 "testconn" #5: initiating Main Mode
105 "testconn" #5: STATE_MAIN_I1: initiate
003 "testconn" #5: received Vendor ID payload [Openswan (this version) 2.6.50dev6 ]
003 "testconn" #5: received Vendor ID payload [Dead Peer Detection]
002 "testconn" #5: transition from state STATE_MAIN_I1 to state STATE_MAIN_I2
107 "testconn" #5: STATE_MAIN_I2: sent MI2, expecting MR2
002 "testconn" #5: transition from state STATE_MAIN_I2 to state STATE_MAIN_I3
109 "testconn" #5: STATE_MAIN_I3: sent MI3, expecting MR3
003 "testconn" #5: received Vendor ID payload [CAN-IKEv2]
002 "testconn" #5: Main mode peer ID is ID_FQDN: '@venera'
002 "testconn" #5: transition from state STATE_MAIN_I3 to state STATE_MAIN_I4
004 "testconn" #5: STATE_MAIN_I4: ISAKMP SA established {auth=OAKLEY_RSA_SIG oursig= theirsig=AQN1dXSAE cipher=aes_128 prf=OAKLEY_SHA2_256 group=modp1536}
002 "testconn" #5: Dead Peer Detection (RFC 3706): enabled
002 "testconn" #6: initiating Quick Mode RSASIG+ENCRYPT+PFS+UP+IKEv2ALLOW+SAREFTRACK {using isakmp#5 msgid:f21e71c9 proposal=AES(12)_128-SHA2_256(5)_256 pfsgroup=OAKLEY_GROUP_MODP1536}
118 "testconn" #6: STATE_QUICK_I1: initiate
002 "testconn" #6: Dead Peer Detection (RFC 3706): enabled
002 "testconn" #6: transition from state STATE_QUICK_I1 to state STATE_QUICK_I2
004 "testconn" #6: STATE_QUICK_I2: sent QI2, IPsec SA established transport mode {ESP=>0xcc4345db <0xa4d5b87f xfrm=AES_256-HMAC_SHA2_256 NATOA=none NATD=none DPD=enabled}


~# ipsec auto --status
000 using kernel interface: netkey
000 interface lo/lo 127.0.0.1 (AF_INET)
000 interface eth1/eth1 192.168.55.17 (AF_INET)
000 %myid = (none)
000 debug none
000  
000 virtual_private (%priv):
000 - allowed 0 subnets: 
000 - disallowed 0 subnets: 
000 WARNING: Either virtual_private= is not specified, or there is a syntax 
000          error in that line. 'left/rightsubnet=vhost:%priv' will not work!
000 WARNING: Disallowed subnets in virtual_private= is empty. If you have 
000          private address space in internal use, it should be excluded!
000  
000 algorithm ESP encrypt: id=2, name=ESP_DES, ivlen=8, keysizemin=64, keysizemax=64
000 algorithm ESP encrypt: id=3, name=ESP_3DES, ivlen=8, keysizemin=192, keysizemax=192
000 algorithm ESP encrypt: id=6, name=ESP_CAST, ivlen=8, keysizemin=40, keysizemax=128
000 algorithm ESP encrypt: id=7, name=ESP_BLOWFISH, ivlen=8, keysizemin=40, keysizemax=448
000 algorithm ESP encrypt: id=11, name=ESP_NULL, ivlen=0, keysizemin=0, keysizemax=0
000 algorithm ESP encrypt: id=12, name=ESP_AES, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: id=13, name=ESP_AES_CTR, ivlen=8, keysizemin=160, keysizemax=288
000 algorithm ESP encrypt: id=14, name=ESP_AES_CCM_A, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: id=15, name=ESP_AES_CCM_B, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: id=16, name=ESP_AES_CCM_C, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: id=18, name=ESP_AES_GCM_A, ivlen=8, keysizemin=160, keysizemax=288
000 algorithm ESP encrypt: id=19, name=ESP_AES_GCM_B, ivlen=12, keysizemin=160, keysizemax=288
000 algorithm ESP encrypt: id=20, name=ESP_AES_GCM_C, ivlen=16, keysizemin=160, keysizemax=288
000 algorithm ESP encrypt: id=22, name=ESP_CAMELLIA, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: id=252, name=ESP_SERPENT, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: id=253, name=ESP_TWOFISH, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP auth attr: id=1, name=AUTH_ALGORITHM_HMAC_MD5, keysizemin=128, keysizemax=128
000 algorithm ESP auth attr: id=2, name=AUTH_ALGORITHM_HMAC_SHA1, keysizemin=160, keysizemax=160
000 algorithm ESP auth attr: id=5, name=AUTH_ALGORITHM_HMAC_SHA2_256, keysizemin=256, keysizemax=256
000 algorithm ESP auth attr: id=6, name=AUTH_ALGORITHM_HMAC_SHA2_384, keysizemin=384, keysizemax=384
000 algorithm ESP auth attr: id=7, name=AUTH_ALGORITHM_HMAC_SHA2_512, keysizemin=512, keysizemax=512
000 algorithm ESP auth attr: id=8, name=AUTH_ALGORITHM_HMAC_RIPEMD, keysizemin=160, keysizemax=160
000 algorithm ESP auth attr: id=9, name=AUTH_ALGORITHM_AES_CBC, keysizemin=128, keysizemax=128
000 algorithm ESP auth attr: id=251, name=AUTH_ALGORITHM_NULL_KAME, keysizemin=0, keysizemax=0
000  
000 algorithm IKE encrypt: id=0, name=(null), blocksize=16, keydeflen=131
000 algorithm IKE encrypt: id=5, name=OAKLEY_3DES_CBC, blocksize=8, keydeflen=192
000 algorithm IKE encrypt: id=7, name=OAKLEY_AES_CBC, blocksize=16, keydeflen=128
000 algorithm IKE hash: id=1, name=OAKLEY_MD5, hashsize=16
000 algorithm IKE hash: id=2, name=OAKLEY_SHA1, hashsize=20
000 algorithm IKE hash: id=4, name=OAKLEY_SHA2_256, hashsize=32
000 algorithm IKE hash: id=6, name=OAKLEY_SHA2_512, hashsize=64
000 algorithm IKE dh group: id=2, name=OAKLEY_GROUP_MODP1024, bits=1024
000 algorithm IKE dh group: id=5, name=OAKLEY_GROUP_MODP1536, bits=1536
000 algorithm IKE dh group: id=14, name=OAKLEY_GROUP_MODP2048, bits=2048
000 algorithm IKE dh group: id=15, name=OAKLEY_GROUP_MODP3072, bits=3072
000 algorithm IKE dh group: id=16, name=OAKLEY_GROUP_MODP4096, bits=4096
000 algorithm IKE dh group: id=17, name=OAKLEY_GROUP_MODP6144, bits=6144
000 algorithm IKE dh group: id=18, name=OAKLEY_GROUP_MODP8192, bits=8192
000 algorithm IKE dh group: id=22, name=OAKLEY_GROUP_DH22, bits=1024
000 algorithm IKE dh group: id=23, name=OAKLEY_GROUP_DH23, bits=2048
000 algorithm IKE dh group: id=24, name=OAKLEY_GROUP_DH24, bits=2048
000  
000 stats db_ops: {curr_cnt, total_cnt, maxsz} :context={0,2,36} trans={0,2,1536} attrs={0,2,2048} 
000  
000 "testconn": 192.168.55.17[@mars]...192.168.55.1[@venera]; erouted; eroute owner: #4
000 "testconn":     myip=unset; hisip=unset; myup=/ramdisk/sbin/ipsec.updown;
000 "testconn":   ike_life: 3600s; ipsec_life: 1200s; rekey_margin: 300s; rekey_fuzz: 50%; keyingtries: 0 
000 "testconn":   policy: RSASIG+ENCRYPT+PFS+UP+IKEv2ALLOW+SAREFTRACK; prio: 32,32; interface: eth1; kind=CK_PERMANENT
000 "testconn":   dpd: action:restart; delay:30; timeout:120;  
000 "testconn":   newest ISAKMP SA: #1; newest IPsec SA: #4; eroute owner: #4;
000 "testconn":   IKE algorithms wanted: AES_CBC(7)_000-SHA2_256(4)_000-MODP1536(5), AES_CBC(7)_000-SHA2_256(4)_000-MODP1024(2); flags=-strict
000 "testconn":   IKE algorithms found:  AES_CBC(7)_128-SHA2_256(4)_256-MODP1536(5)AES_CBC(7)_128-SHA2_256(4)_256-MODP1024(2)
000 "testconn":   IKE algorithm newest: AES_CBC_128-SHA2_256-MODP1536
000 "testconn":   ESP algorithms wanted: AES(12)_000-SHA2_256(5)_000; flags=-strict
000 "testconn":   ESP algorithms loaded: AES(12)_128-SHA2_256(5)_256
000 "testconn":   ESP algorithm newest: AES_256-HMAC_SHA2_512; pfsgroup=<Phase1>
000  
000 #4: "testconn":500 IKEv1.0 STATE_QUICK_R2 (IPsec SA established); EVENT_SA_REPLACE in 960s; newest IPSEC; eroute owner; isakmp#2; idle; import:not set
000 #4: "testconn" esp.e9886f8f@192.168.55.1 esp.c90cb992@192.168.55.17 ref=0 refhim=4294901761
000 #2: "testconn":500 IKEv1.0 STATE_MAIN_R3 (sent MR3, ISAKMP SA established); EVENT_SA_REPLACE in 3360s; lastdpd=0s(seq in:17109 out:0); idle; import:not set
000 #3: "testconn":500 IKEv1.0 STATE_QUICK_I2 (sent QI2, IPsec SA established); EVENT_SA_REPLACE in 673s; isakmp#1; idle; import:admin initiate
000 #3: "testconn" esp.f9aac72e@192.168.55.1 esp.4103f462@192.168.55.17 ref=0 refhim=4294901761
000 #1: "testconn":500 IKEv1.0 STATE_MAIN_I4 (ISAKMP SA established); EVENT_SA_REPLACE in 3151s; newest ISAKMP; lastdpd=0s(seq in:0 out:0); idle; import:admin initiate
000
