### ISSUE TITLE
ipsec verify: encountered errors

### ISSUE THREAD

**Issue by gzldx** [xelerance/Openswan#208]
![_20160919095041](https://cloud.githubusercontent.com/assets/2508193/18620993/6edab870-7e4f-11e6-837b-a7f33db9e4ab.png)

**Checking 'ip' command                             	[IP XFRM BROKEN]**

No Failed error, but some NOT IMPLEMENTED notice and a red error, can anyone help??

**Comment by gzldx** [comment]
Checking 'ip' command [IP XFRM BROKEN]

what is this problem?

**Comment by gzldx** [comment]
Checking 'ip' command [IP XFRM BROKEN]

what is this problem?

**Comment by shussain** [comment]
What Linux distro are you using? Could you also specify the architecture.

What happens when you run: _[sudo] ip xfrm polcy_

**Comment by shussain** [comment]
Is the issue still occurring for you? What happens when  you run the above command (_[sudo] ip xfrm policy_)

**Comment by gzldx** [comment]
Yes, thank you for you reply! I am so sorry I was busy these two days.

I log out the display:
>ip xfrm policy
src ::/0 dst ::/0 
	dir 4 priority 0 ptype main 
src ::/0 dst ::/0 
	dir 3 priority 0 ptype main 
src 0.0.0.0/0 dst 0.0.0.0/0 
	dir 4 priority 0 ptype main 
src 0.0.0.0/0 dst 0.0.0.0/0 
	dir 3 priority 0 ptype main 
src 0.0.0.0/0 dst 0.0.0.0/0 
	dir 4 priority 0 ptype main 
src 0.0.0.0/0 dst 0.0.0.0/0 
	dir 3 priority 0 ptype main 
src 0.0.0.0/0 dst 0.0.0.0/0 
	dir 4 priority 0 ptype main 
src 0.0.0.0/0 dst 0.0.0.0/0 
	dir 3 priority 0 ptype main 
src 0.0.0.0/0 dst 0.0.0.0/0 
	dir 4 priority 0 ptype main 
src 0.0.0.0/0 dst 0.0.0.0/0 
	dir 3 priority 0 ptype main

What was the ploblem?

**Comment by gzldx** [comment]
service ipsec status
IPsec running  - pluto pid: 21233
pluto pid 21233
No tunnels up

**Comment by shussain** [comment]
Thank you for the _ip xfrm policy_. 

Can you please give the output of _ip xfrm_?

**Comment by gzldx** [comment]
ip xfrm state?? I don't understand.

**Comment by gzldx** [comment]
>ip xfrm state

display nothing

**Comment by shussain** [comment]
> ip xfrm state?? I don't understand.

Please just run: _ip xfrm_. It will display the usage text. _ipsec verify_ searches for the string "XFRM-OBJECT" in the text 

So on my machine, I have:

_%sudo ip xfrm
Usage: ip xfrm XFRM-OBJECT { COMMAND | help }
where  XFRM-OBJECT := state | policy | monitor_

I just want to confirm, you don’t have anything different. I suspect you probably have the right result, 

If _ip xfrm_ comes with the right results, please rerun _ipsec verify_ as sudo or root.

**Comment by gzldx** [comment]
[root@LDX ~]# ip xfrm
Usage: ip xfrm XFRM_OBJECT { COMMAND | help }
where  XFRM_OBJECT := { state | policy | monitor }

**Comment by gzldx** [comment]
It seems nothing different..

**Comment by gzldx** [comment]
![_20160919095041](https://cloud.githubusercontent.com/assets/2508193/18620944/91bf612a-7e4e-11e6-9e44-3eef46126939.png)

**Comment by gzldx** [comment]
It is my DigitalOcean VPS, the linux version is CentOS 6.5.

**Comment by gzldx** [comment]
I just find a note..
http://gpdb.docs.pivotal.io/4380/admin_guide/topics/ipsec.html

Note: The result for Checking 'ip' command may be [IP XFRM BROKEN], depending on the version of iproute on your system. This can be a misdiagnosis caused by a change in IP XFRM message output between iproute versions.

I think there is some problems in the iproute, but I don't know how to fixed it..

**Comment by shussain** [comment]
Ahhh... I see the issue. The verify code is looking for "XFRM-OBJECT" while the version you have is "XFRM_OBJECT", hence the error.

**Comment by shussain** [comment]
I have fixed the issue with commit 37d9af09aab4ed42945860bce607e5e24b459fb5 (https://github.com/xelerance/Openswan/commit/37d9af09aab4ed42945860bce607e5e24b459fb5) in the 2.6.50dev branch. It will be merged into master before November 8th and there will be a new release.

You can:
* temporarily add that commit to your repo and rebuild
* OR build using the 2.6.50dev branch
* OR ignore the _IP XFRM BROKEN_ messge (_ipsec verify_ provides diagnostic info, it won't prevent you from establishing an IPsec tunnel)

**Comment by gzldx** [comment]
OK, I try to ignore it..Thank you for you solution.

**Comment by shussain** [comment]
Good to hear.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by gzldx** [comment]
Last time you said the ipsec result 'IP XFRM BROKEN' messge won't prevent from establishing an ipsec tunnel，i try，but i can't connect to the ipsec server.

**Comment by shussain** [comment]
How odd.   @gzldx I got the previous message "Last time you said..." 11 times. I have gone ahead and deleted the multiple versions of the message.

As for your IPsec tunnle, can you please provide a copy of your IPsec connection and a quick description of what youa re trying to do?  You mentioned an IPsec server, dos that mean you have an existing, workign IPseerver that is known to establish connection?

**Comment by gzldx** [comment]
Sorry about that.. There is something wrong with my network.

Today morning, I try the ipsec tool racoon, it finish my network connect, now i can connect to my vps by using ipsec. 

This question can be closed. Thank you very much for your help.
