### ISSUE TITLE
Ipsec verify 

### ISSUE THREAD

**Issue by pesaply** [xelerance/Openswan#210]
hecking if IPsec got installed and started correctly:

Version check and ipsec on-path                     [OK]
Openswan U2.6.49-1-g91936d3/K4.4.0-38-generic (netkey)
See `ipsec --copyright' for copyright information.
Checking for IPsec support in kernel                [OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects                [OK]
         ICMP default/accept_redirects              [NOT DISABLED]

  Disable /proc/sys/net/ipv4/conf/*/accept_redirects or NETKEY will cause act on or cause sending of bogus ICMP redirects!

```
     XFRM larval drop                           [OK]
```

Hardware random device check                        [N/A]
Two or more interfaces found, checking IP forwarding    [OK]
Checking rp_filter                                  [ENABLED]
 /proc/sys/net/ipv4/conf/all/rp_filter              [ENABLED]
Checking that pluto is running                      [OK]
 Pluto listening for IKE on udp 500                 [OK]
 Pluto listening for IKE on tcp 500                 [NOT IMPLEMENTED]
 Pluto listening for IKE/NAT-T on udp 4500          [OK]
 Pluto listening for IKE/NAT-T on tcp 4500          [NOT IMPLEMENTED]
 Pluto listening for IKE on tcp 10000 (cisco)       [NOT IMPLEMENTED]
Checking NAT and MASQUERADEing                      [TEST INCOMPLETE]
Checking 'ip' command                               [OK]
Checking 'iptables' command                         [OK]

ipsec verify: encountered errors

I Did Try To Enable The tcp port 4500 tcp 500  Port for Ike  but when i restart ipsec am still getting the same errors ,  the vpn does not come up , i tryed restarting my machine still same issue  please help

**Comment by shussain** [comment]
Hello,
   Have you started the ipsec service and established a connection? 

  Can you please provide your ipsec.conf (in /etc/ipsec.conf) and the results of: _[sudo] ipsec auto --status_

**Comment by pesaply** [comment]
Hello , Yes I Did restart couple of times 
000 #8: "cisco":4500 IKEv1.0 STATE_MAIN_I4 (ISAKMP SA established); EVENT_SA_REPLACE in 27686s; newest ISAKMP; lastdpd=394s(seq in:2729 out:0); idle; import:admin initiate
000  
000 192.168.1.11/32:48690 -6-> 10.0.0.0/32:4000 => %hold 0    %acquire-netlink

**Comment by shussain** [comment]
So I presume you are trying to establish an IPsec tunnel with Cisco endpoint.

What are the requirements for the Cisco endpoint? And can you please provide your ipsec.conf file?

If you would prefer not to have that information visible to the public, we can correspond by email. You can email shussain@xelerance.com

**Comment by shussain** [comment]
Hi. Is this issue still occurring? 

Can I go ahead and close this ticket?

**Comment by pesaply** [comment]
Yes Yes Sorry I Used Ngs3 With  Cisco asa vm , and it works , but if we can close this i like to share my ipsec.conf file , for the benefits of others
