### ISSUE TITLE
musl support

### ISSUE THREAD

**Issue by joerg-krause** [xelerance/Openswan#214]
I am working on building Openswan with the musl C library. For this the following changes are necessary:

1. provide an alternative implementation for glob GNU extensions (`GLOB_BRACE`, `GLOB_NOMATCH`) by using libglob as musl does not have it
2. define `IP_IPSEC_REFINFO` and `IP_IPSEC_BINDREF` for `USE_MAST=false`
3. define `OLD_RESOLVER` for all non-GLIBC libs
4. provide an alternative implementation for `qsort_r()` as musl does not have it

I am unsure about point 2 and 4.

2. `IP_IPSEC_REFINFO` is used [here](https://github.com/xelerance/Openswan/blob/91936d3732586f6879e7eb7e8eaea420ef5796a9/programs/pluto/kernel.c#L3272), but the inclusion of the definition depends on [`KLIPS_MAST`](https://github.com/xelerance/Openswan/blob/91936d3732586f6879e7eb7e8eaea420ef5796a9/programs/pluto/kernel.c#L63-L65).
4. Which `qsort_r()` implemention?

If there is some interest in supporting the musl C library, please let me know, thanks!

**Comment by letoams** [comment]
I'm interested in libreswan properly supporting alternative libc implementations. If you test with libreswan, please let us know if you see any issues and let the libreswan project know.
libreswan does not set OLD_RESOLVER (but probably does not need it) and does not use qsort_r() 
But it does use the GLOB_BRACE and GLOB_NOMATCH extensions as well.

**Comment by shussain** [comment]
Thank you for your work. We are definitely interested in supporting musl C library

**Comment by joerg-krause** [comment]
@shussain Can you have a look at point 2 and 4?

If `LKIPS_MAST` is not defined than musl build breaks because `IP_IPSEC_REFINFO` is undefined in `saref_init()`.

Is `qsort_r()` really necessary?

**Comment by shussain** [comment]
@joerg-krause    Have address point 2 (if KLIPS_MAST has not been defined) in the 2.6.50dev branch. That branch will be merged to master in a couple of weeks when we do a 2.6.50 release

As for point 4 (qsort_r), we do use it in a couple of places. In order to address your concern, we could include https://github.com/freebsd/freebsd/blob/master/lib/libc/stdlib/qsort.c  (if __GLIBC__ is not defined)

**Comment by shussain** [comment]
We are now using qsort() (commit 262e4f3dc9ca0d00fbdf1ced7e63ef412f59798b). 

Both commits are in 2.6.50 release
