### ISSUE TITLE
pending Quick Mode took too long -- replacing phase 1 on multiple subnets

### ISSUE THREAD

**Issue by bartlubberdink** [xelerance/Openswan#217]
Hello,

we face an issue with openswan 2.6.49 (klips) on Debian 8.
VPN's work fine with one subnet on each site.
but, when we define a VPN configuration with more than one subnet (left or right or both), the VPN comes online without any problems, and works fine.
but after aprox. 30 seconds, the logfile starts to show lines like:
pending Quick Mode took too long with x.x.x.x -- replacing phase 1

this will continue forever, until the timer expires, and the specific phase 2 entry goes down (unrouted).
A manual up won't work either.
There is always 1 phase2 entry without any problems. and phase1 is also online (including DPD).

To re-enable all phase2 tunnels, a complete down of phase1 needs to be done manually.

Example config:
conn megen01
        auto=start
        type=tunnel
        left=xx.xx.xx.xx
        leftsubnets={aa.aa.aa.aa/32,}
        right=zz.zz.zz.zz
        rightid=zz.zz.zz.zz
        rightsubnets={bb.16.25.250/32,cc.16.10.103/32,dd.16.56.100/32,ee.16.9.2/32,}
        keyexchange=ike
        ike=aes256-sha1-modp1536
        ikelifetime=8h
        auth=esp
        pfs=no
        authby=secret
        esp=aes256-sha1
        rekey=yes
        keyingtries=3
        keylife=1h
        aggrmode=no
        dpddelay=30
        dpdtimeout=120
        dpdaction=restart

It looks like the phase2 SA's aren't connected to the common phas1 SA?

Does someone know what might be wrong here?

Thanks in advance.

Bart Lubberdink

**Comment by letoams** [comment]
As workaround you can try using a separate conn per subnet-subnet. The con alias code has problems. Some were fixed in libreswan but we are still not confident all alias code works properly

**Comment by bartlubberdink** [comment]
Hello letoams,

putting them in seperate connections results in an even bigger problem.
The first one put online works fine, but the others won't work at all.

the strange part her, we also have a configuration on the same unit with two seperate connections, and that works initialy (bringing online works), but the problem with the timeout is exactly the same.

Regards,
Bart Lubberdink

**Comment by letoams** [comment]
On Wed, 7 Dec 2016, bartlubberdink wrote:

> we face an issue with openswan 2.6.49 (klips) on Debian 8.
> VPN's work fine with one subnet on each site.
> but, when we define a VPN configuration with more than one subnet (left or right or both),
> the VPN comes online without any problems, and works fine.
> but after aprox. 30 seconds, the logfile starts to show lines like:
> pending Quick Mode took too long with x.x.x.x -- replacing phase 1

Does the same happen if you do not use subnetS= but use separate conns
for these?

Example:

> leftsubnets={aa.aa.aa.aa/32,}
> rightsubnets={bb.16.25.250/32,cc.16.10.103/32,dd.16.56.100/32,ee.16.9.2/32,}


conn first
   leftsubnet=aa.aa.aa.aa/32
   rightsubnet=bb.16.25.250/32

conn second
   leftsubnet=aa.aa.aa.aa/32
   rightsubnet=bb.16.25.250/32

etc.

This would help us narrow down the bug to the alias code that is related
to the left/rightsubnetS= option.

Paul
Note I'm looking at this with libreswan, but openswan has the same code
for this feature

**Comment by bartlubberdink** [comment]
Hello Paul,

changed the config to this:

conn megen01
        auto=start
        type=tunnel
        left=a.a.a.a
        leftsubnet=aa.aa.aa.aa/32
        right=zz.zz.zz.zz
        rightid=zz.zz.zz.zz
        rightsubnet=bb.16.25.250/32
        keyexchange=ike
        ike=aes256-sha1-modp1536
        ikelifetime=8h
        auth=esp
        pfs=no
        authby=secret
        esp=aes256-sha1
        rekey=yes
        keyingtries=3
        keylife=1h
        aggrmode=no
        dpddelay=30
        dpdtimeout=120
        dpdaction=restart

conn megen02
        auto=start
        type=tunnel
        left=a.a.a.a
        leftsubnet=aa.aa.aa.aa/32
        right=zz.zz.zz.zz
        rightid=zz.zz.zz.zz
        rightsubnet=cc.16.10.103/32
        keyexchange=ike
        ike=aes256-sha1-modp1536
        ikelifetime=8h
        auth=esp
        pfs=no
        authby=secret
        esp=aes256-sha1
        rekey=yes
        keyingtries=3
        keylife=1h
        aggrmode=no
        dpddelay=30
        dpdtimeout=120
        dpdaction=restart

conn megen03
        auto=start
        type=tunnel
        left=a.a.a.a
        leftsubnet=aa.aa.aa.aa/32
        right=zz.zz.zz.zz
        rightid=zz.zz.zz.zz
        rightsubnet=dd.16.56.100/32
        keyexchange=ike
        ike=aes256-sha1-modp1536
        ikelifetime=8h
        auth=esp
        pfs=no
        authby=secret
        esp=aes256-sha1
        rekey=yes
        keyingtries=3
        keylife=1h
        aggrmode=no
        dpddelay=30
        dpdtimeout=120
        dpdaction=restart

conn megen04
        auto=start
        type=tunnel
        left=a.a.a.a
        leftsubnet=aa.aa.aa.aa/32
        right=zz.zz.zz.zz
        rightid=zz.zz.zz.zz
        rightsubnet=ee.16.9.2/32
        keyexchange=ike
        ike=aes256-sha1-modp1536
        ikelifetime=8h
        auth=esp
        pfs=no
        authby=secret
        esp=aes256-sha1
        rekey=yes
        keyingtries=3
        keylife=1h
        aggrmode=no
        dpddelay=30
        dpdtimeout=120
        dpdaction=restart


then, bringing megen01 up, works fine.
bringing megen02 up.. doesn't work.
with the same error on the logfile:
pending Quick Mode with zz.zz.zz.zz "megen02" took too long -- replacing phase 1

i have a debug log available (not for public upload...)

Regards,
Bart

**Comment by bartlubberdink** [comment]
did some more research,
changed from KLIPS to NETKEY.... same problem.

From the debug i found this:
| next event EVENT_PENDING_DDNS in 0 seconds
| *time to handle event
| at 2016-12-20 11:00:49 handling event EVENT_PENDING_DDNS
| event after this is EVENT_PENDING_PHASE2 in 60 seconds
| inserting event EVENT_PENDING_DDNS, timeout in 60 seconds (head of queue)
| next event EVENT_PENDING_DDNS in 60 seconds
|
| next event EVENT_PENDING_DDNS in 0 seconds
| *time to handle event
| at 2016-12-20 11:01:49 handling event EVENT_PENDING_DDNS
| event after this is EVENT_PENDING_PHASE2 in 0 seconds
| inserting event EVENT_PENDING_DDNS, timeout in 60 seconds
| event added after event EVENT_PENDING_PHASE2
| at 2016-12-20 11:01:49 handling event EVENT_PENDING_PHASE2
| event after this is EVENT_PENDING_DDNS in 60 seconds
| inserting event EVENT_PENDING_PHASE2, timeout in 120 seconds
| event added after event EVENT_PENDING_DDNS
| pending review: connection "megen01/1x3" being checked
| pending review: connection "megen01/1x3" not time for review
| pending review: connection "megen01/1x2" being checked
|   no additional DNS answers,  not re-attempting
pending Quick Mode with 192.168.255.137 "megen01/1x2" took too long -- replacing phase 1
| pending review: connection "megen01/1x1" being checked
|   no additional DNS answers,  not re-attempting
pending Quick Mode with 192.168.255.137 "megen01/1x1" took too long -- replacing phase 1
| next event EVENT_PENDING_DDNS in 60 seconds
|
| next event EVENT_PENDING_DDNS in 0 seconds
| *time to handle event
| at 2016-12-20 11:02:49 handling event EVENT_PENDING_DDNS
| event after this is EVENT_PENDING_PHASE2 in 60 seconds
| inserting event EVENT_PENDING_DDNS, timeout in 60 seconds (head of queue)
| next event EVENT_PENDING_DDNS in 60 seconds

Not sure what openswan needs regarding DNS. it doesn't do any DNS lookups on the network.

Regards,
Bart

**Comment by bartlubberdink** [comment]
Hello Paul,

Working our way back, things are working at 2.6.46.
same server, just an older version of openswan.
On 2.6.47 and 2.6.48, the error persist.

Regards,
Bart

**Comment by letoams** [comment]
I have not used openswan since we forked libreswan from openswan 2.6.38. If you can test libreswan-3.18, which should be a drop-in replacement. If libreswan has a similar bug, then I can look at it (and we should probably take that discussion to the libreswan github section
