### ISSUE TITLE
ASSERTION FAILED at lib/libpluto/packet.c:1729 

### ISSUE THREAD

**Issue by viddatw** [xelerance/Openswan#218]
Hi all,

The following is my client config

version 2.0
config setup
        dumpdir=/var/run/pluto/
        oe=off
        nat_traversal=yes
        protostack=netkey

conn aaa
        aggrmode=yes
        authby=rsasig
        left=192.168.41.101
        leftsourceip=192.168.127.253
        leftnexthop=%defaultroute
        right=122.116.x.x (public IP address)
        leftsubnet=192.168.130.0/24
        rightsubnet=10.0.0.0/24
        leftrsasigkey=%cert
        rightrsasigkey=%cert
        leftcert=localcert2.pem
        rightcert=remotecert2.pem
        type=tunnel
        ike=3des-md5;modp1024!
        phase2=esp
        phase2alg=3des-md5!
        auto=start
        pfs=yes
        rekeymargin=9m
        rekeyfuzz=100%
        keyingtries=0
        ikelifetime=60m
        salifetime=480m

----
When aggressive mode is enabled and I use X.509 as my authentication way. But when I connected to a remote server, openswan has failed.
The error message is :
---
 "aaa" #1: ASSERTION FAILED at /work/work/vpn/Openswan_bak/lib/libpluto/packet.c:1729: pl[NOFFSETOF_isa_np] == ISAKMP_NEXT_NONE || pl[NOFFSETOF_isa_np] == ISAKMP_NEXT_HASH

But this situation did not occur when I used main mode.

---

I have tried to debug this issue and found that the message is located in lib/libpluto/packet.c:
bool
out_modify_previous_np(u_int8_t np, pb_stream *outs){
...
passert(pl[NOFFSETOF_isa_np] == ISAKMP_NEXT_NONE ||
                pl[NOFFSETOF_isa_np] == ISAKMP_NEXT_HASH );
...
}

I tried to print out value of pl[NOFFSETOF_isa_np] and found the value is 9.

So the following is my patch:

---

diff --git a/lib/libpluto/packet.c b/lib/libpluto/packet.c
index ce312b9..6086225 100644
--- a/lib/libpluto/packet.c
+++ b/lib/libpluto/packet.c
@@ -1726,7 +1726,8 @@ out_modify_previous_np(u_int8_t np, pb_stream *outs)
     if (left == NSIZEOF_isakmp_hdr) {
        /* no payloads, just the isakmp_hdr: insert np here */
        passert(pl[NOFFSETOF_isa_np] == ISAKMP_NEXT_NONE ||
 `-`               pl[NOFFSETOF_isa_np] == ISAKMP_NEXT_HASH);
 `+`               pl[NOFFSETOF_isa_np] == ISAKMP_NEXT_HASH ||
 `+`               pl[NOFFSETOF_isa_np] == ISAKMP_NEXT_SIG);
        pl[NOFFSETOF_isa_np] = np;
     } else {
        pl += NSIZEOF_isakmp_hdr;       /* skip over isakmp_hdr */

---
If I use this patch, my client will connect to sever successfully.

I wonder that why the next payload type does not contain ISAKMP_NEXT_SIG.

Or my solution is a mistake.

**Comment by shussain** [comment]
I believe this has been fixed in 2.6.50

Can you please confirm?
