### ISSUE TITLE
connection drop regularly

### ISSUE THREAD

**Issue by nick-zhuyj** [xelerance/Openswan#222]
We have setup VPN connection with openswan 2.6.46. And the connection drops regularly. And we found the following logs:

Jan 19 15:14:39 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2650: received and ignored informational message
Jan 19 15:58:26 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2671: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+SAREFTRACK to replace #2670 {using isakmp#2650 msgid:f9eb53f7 proposal=3DES(3)_192-SHA1(2)_160 pfsgroup=OAKLEY_GROUP_MODP1024}
Jan 19 15:58:56 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2671: ERROR: netlink response for Add SA esp.94d310d2@x.y.z included errno 3: No such process
Jan 19 15:58:56 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2671: state #2671: failed to setup incoming SA
Jan 19 15:59:00 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2671: ERROR: netlink response for Add SA esp.94d310d2@x.y.z included errno 3: No such process
Jan 19 15:59:00 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2671: state #2671: failed to setup incoming SA
Jan 19 15:59:08 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2671: ERROR: netlink response for Add SA esp.94d310d2@x.y.z included errno 3: No such process
Jan 19 15:59:08 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2671: state #2671: failed to setup incoming SA
Jan 19 15:59:25 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2671: ERROR: netlink response for Add SA esp.94d310d2@x.y.z included errno 3: No such process
Jan 19 15:59:25 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2671: state #2671: failed to setup incoming SA
Jan 19 16:04:25 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2671: deleting state #2671 (STATE_QUICK_I1)
Jan 19 16:14:29 host001 pluto[2465343]: "4d61dda4-5897-4ee4-ac82-5c161f3c3da2/0x1" #2670: IPsec SA expired (LATEST!)

**Comment by shussain** [comment]
The rekey code has been updated with newer versions of OSW
