### ISSUE TITLE
Child SA rekey and nhelpers=0 doesn't work.

### ISSUE THREAD

**Issue by ppavan123** [xelerance/Openswan#238]
I tried to check Parent SA reauth and Child SA rekey feature in Openswan-2.6.49.1 release. The reauth works fine but the child SA rekey fails. 

Setup:

Strongswan (Initiator) ========= Openswan (Responder)

Opesnswan ipsec.conf:
# basic configuration
config setup
 dumpdir=/var/run/pluto/
 virtual_private=%v4:0.0.0.0/0
 oe=off
 protostack=klips
 interfaces="ipsec0=eth0"
 nhelpers=1
 plutodebug="all"

conn openswan
 ikev2=insist
 authby=secret
 left=192.168.10.215
 leftsubnet=192.168.20.0/24
 right=192.168.10.214
 rightsubnet=192.168.30.0/24
 ike=aes128-sha1;modp2048
 phase2=esp
 phase2alg=aes128-sha1
 pfs=yes
 rekey=yes
 ikelifetime=8h
 keylife=1h
 rekeymargin=10s
 keyingtries=2
 type=tunnel
 auto=add

Openswan ipsec.secrets:
192.168.10.215 192.168.10.214 : PSK "ipsec"

Strongswan ipsec.conf:

config setup
        charondebug="ike 4, chd 4, knl 4, mgr 4, net 4, esp 4"

conn %default
         ikelifetime=10m
         keylife=1m
         rekeymargin=10s
         rekeyfuzz = 100%
         keyingtries=1
         keyexchange=ikev2

conn strongswan
        authby=secret
        left=192.168.10.214
        leftsubnet=192.168.30.0/24
        leftfirewall=yes
        right=192.168.10.215
        rightsubnet=192.168.20.0/24
        ike=aes128-sha1-modp2048
        esp=aes128-sha1-modp2048
        rekey=yes
        type=tunnel
        auto=start

Strongswan ipsec.secrets:
192.168.10.214 192.168.10.215 : PSK "ipsec"

After 1 min of tunnel establishment, strongswan sends CREATE_CHILD_SA request but openswan pluto asserts while handling event in timer.c. After that tunnel gets dropped.
If I configure hhelpers=0 in Openswan, it restarts while processing IKE_INIT message.

**Comment by shussain** [comment]
Yes, there was a bug with nhelpers. The fix is in 2.6.50dev branch (commit 2e93318cb4fdf42a0e09a47251d7f99206974a19)

**Comment by ppavan123** [comment]
Thanks for your quick reply. 
But the problem still persists. Without helpers the pluto process does all cryptographic operations and returns STF_INLINE which causes pluto restart.

**Comment by letoams** [comment]
On Tue, 25 Apr 2017, ppavan123 wrote:

> Thanks for your quick reply.
> But the problem still persists. Without helpers the pluto process does all cryptographic operations and
> returns STF_INLINE which causes pluto restart.

I tested nhelpers=0 on libreswan by changing our test case
interop-ikev2-strongswan-35-ipsec-rekey and it passed. It did not
crash and the rekey happened successfully.

Paul

**Comment by ppavan123** [comment]
Does the rekey implementation is same among openswan and libreswan ?
I tried the above test case with openswan-2.6.49.1. The helper=0 and child rekey issues are independent.
1. With nhelpers=0, IKEv2 tunnel doesn't establish properly.
2. With nhelpers=1, tunnel gets established successfully but rekey fails.

**Comment by letoams** [comment]
On Tue, 25 Apr 2017, ppavan123 wrote:

> Does the rekey implementation is same among openswan and libreswan ?

No. the IKEv2 stack in libreswan has seen five more years of
development since forked from openswan due to a trademark conflict:

https://nohats.ca/wordpress/libreswan/

> I tried the above test case with openswan-2.6.49.1. The helper=0 and child rekey issues are independent.
>
>  1. With nhelpers=0, IKEv2 tunnel doesn't establish properly.
>  2. With nhelpers=1, tunnel gets established successfully but rekey fails.

I've tested both on libreswan, and it works. I did not save a new test
case for the nhelpers=0 case but tested it manually. The original interop
rekey testcases can be seen at:


https://github.com/libreswan/libreswan/tree/master/testing/pluto/interop-ikev2-strongswan-29-rekey
https://github.com/libreswan/libreswan/tree/master/testing/pluto/interop-ikev2-strongswan-35-ipsec-rekey
https://github.com/libreswan/libreswan/tree/master/testing/pluto/interop-ikev2-strongswan-35-ipsec-rekey-pfs

Our daily testruns that run these can be found: http://testing.libreswan.org/

Paul
