### ISSUE TITLE
Openswan on custom port

### ISSUE THREAD

**Issue by iyappan-dcis** [xelerance/Openswan#240]
Hello,

I am trying to establish connection between two opwnswan servers. But server-1 is listening on custom ports 4600 and 501.  How do I configure server-2 to make a connection with server-1 on ports 4600 and 501. 

I tried configuring like "rightikeport=4600" which does not work.

Please advise.

**Comment by iyappan-dcis** [comment]
Can someone provide a suggestion ?

**Comment by letoams** [comment]
There is a global ikeport= option only, not a per-conn one.

I'm pretty sure though that setting it won't work as expected as the code isn't consistent with it. We have the same issue in libreswan where this code is getting cleaned up while we are adding tcp support

Paul

**Comment by mcr** [comment]
Openswan consistently uses the ikeport= setting as "port 500" throughout the
code.   One can consistently set the "port 4500" via another setting as well.
This setting exists primarily to enable testing of multiple copies of pluto
against itself on a single host.

As Paul said, there is little support for per-conn settings of the remote
port, although the port numbers are carried in the structures internally.
If it's just a single peer (which will be a responder) that has to have an
odd port, I suggest an iptables port remap in POSTROUTING may be the simplest
answer.  If the local openswan can not run on port 500, ikeport= will help.
If you need it to run on multiple ports, use iptables to remap the others.
This *will* trigger nat detection, which is actually appropriate.

IKEv2 mandates that all replies go to the port it was sent from, not port-500.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by letoams** [comment]
there are actually a few hardcoded 500 /4500 references unless you changed that since the fork of libreswan.
Also, IKEv2 only mandates that for the non-mobike case. And if you update the port dynamically without actually migrating the IPsec SA, then you just break things badly because DPD will work but IPsec flow is broken so you cannot even recover. It's better to do nothing at all so DPD can restart the connection. (even better is MOBIKE support, which is experimental in libreswan and will be in 3.22)

hacking  things with iptables is madness

**Comment by iyappan-dcis** [comment]
Thank you Michael Richardson and Paul for your time. I have attached a document on the setup. Please take some time to go through it and provide me your advise. 

Thanks in Advance.
[IPSecSite-SiteVPNSetup (3).pdf](https://github.com/xelerance/Openswan/files/1074503/IPSecSite-SiteVPNSetup.3.pdf)

**Comment by iyappan-dcis** [comment]
@letoams @mcr Please can you suggest something.

**Comment by letoams** [comment]
Sorry, I cannot.
Libreswan is working on adding tcp suppprt, so we have someone working on cleaning up this code but i don't know if running Ike on a nonstandard port works
