### ISSUE TITLE
Feature: Android ipsec psk client

### ISSUE THREAD

**Issue by dipenpatel235** [xelerance/Openswan#242]
Hello.
I have done ipsec server setup using openswan.
Now I want to connect using Android client using source code.
But not found anything related ipsec client coding for Android.
So if you have your Android client coming or hint so please help .

Thanks

**Comment by mcr** [comment]
In the opensource space, strongswan has a "libipsec" which uses the Android
"VPN" connect interface to do all of IPsec in userspace.

Android also has IKEv1 support built-in (via racoon), but it's not terribly
easy to configure.  I've heard a rumour that there will may be a full IKEv2
client soon.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by dipenpatel235** [comment]
Thanks for help ful info.
But in strongswan client also not given IPsec PSK Xauth based related.

Thanks.
