### ISSUE TITLE
in buildlin.sh gmp.h position

### ISSUE THREAD

**Issue by jejayhe** [xelerance/Openswan#243]
in buildlin.sh, it checks this path /usr/include/gmp.h
while in ubuntu 17.04, when I install libgmp-dev or libgmp3-dev, it's installed to /usr/include/x86_64-linux-gnu/gmp.h

**Comment by shussain** [comment]
Thank you for the information.
In 17.04: the libgmp-dev has the /usr/include/gmp.h in /usr/include/CGAL/gmp.h

I will submit a patch but for now, you can remove that check or the path. You should then be able to build Openswan without any further issues.

**Comment by shussain** [comment]
Added commit c2daa0fa9273326df34d9df24d8fd01e3c79fec0   in 2.6.51dev branch
