### ISSUE TITLE
openswan on RHEL - can't start IPSec service

### ISSUE THREAD

**Issue by rrands1** [xelerance/Openswan#247]
Hey all - first time post - very new to Linux.  I am following [this guide](http://walkintocloud.com/index.php/2016/06/16/openswan-connecting-two-vpcs-different-regions-amazon-aws/) to try and set up Openswan between two AWS regions.  I get to the point of starting the IPSec services (service IPSec start), but get errors.  
==================
[root@ip-10-10-0-181 ~]# service ipsec start
Redirecting to /bin/systemctl start  ipsec.service
Job for ipsec.service failed because the control process exited with error code. See "systemctl status ipsec.service" and "journalctl -xe" for details.
==================

Journalctl -xe -l sez:
-- Unit ipsec.service has begun starting up.
Jul 06 12:37:33 ip-10-10-0-181.ec2.internal addconn[2096]: cannot load config '/etc/ipsec.conf': /etc/ipsec.d/EastVPC-to-WestVPC.conf:2: syntax error, unexpected KEYWORD, expecting $end [type]
Jul 06 12:37:33 ip-10-10-0-181.ec2.internal systemd[1]: ipsec.service: control process exited, code=exited status=3
Jul 06 12:37:33 ip-10-10-0-181.ec2.internal systemd[1]: Failed to start Internet Key Exchange (IKE) Protocol Daemon for IPsec.
-- Subject: Unit ipsec.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
=================

I have reviewed the ipsec.conf file, as well as the EastVPC-to-WestVPC.conf file (contents below), but can't find any obvious errors.  Would anyone be able to help me figure out what is wrong, please?

I appreciate it very much!

-randy

IPSEC.conf contents:  (only putting lines I added...)
--------------------------
include /etc/ipsec.d/*.conf
plutostderrlog=/tmp/pluto.log
--------------------------

EastVPC-to-WestVPC.conf contents:
--------------------------
conn EastVPC-to-WestVPC
type=tunnel
authby=secret
left=%defaultroute
leftid=34.230.100.137
leftnexthop=%defaultroute
leftsubnet=10.10.0.0/21
right=35.163.70.44
rightsubnet=10.20.0.0/21
pfs=no
auto=start
----------------------------

**Comment by shussain** [comment]
Hi. Can you please indent everything below _conn EastVPC-to-WestVPC_

**Comment by rrands1** [comment]
Hi, and thank you - I did indent the contents of that file - I am getting a different error on 'service ipsec start' now - here is the output from 'Journalctl -xe -l':
-----------------------------
-- Unit ipsec.service has begun starting up.
Jul 06 14:04:54 ip-10-10-0-181.ec2.internal addconn[2405]: cannot load config '/etc/ipsec.conf': /etc/ipsec.conf:64: syntax error, unexpected INCLUDE [include]
Jul 06 14:04:54 ip-10-10-0-181.ec2.internal systemd[1]: ipsec.service: control process exited, code=exited status=3
------------------------

So it would appear that my line in the IPSec.conf is incorrect - here is what I have presently:
# For example connections, see your distribution's documentation directory,
# or https://libreswan.org/wiki/
#
# There is also a lot of information in the manual page, "man ipsec.conf"
#
# It is best to add your IPsec connections as separate files in /etc/ipsec.d/
        include /etc/ipsec.d/*.conf
#       plutostderrlog=/tmp/pluto.log
-------------------------

Any thoughts on that?  It seems to be trying to include it, as it had been throwing an error from the actual .conf file before.


Thank you!

**Comment by shussain** [comment]
Can you (re)post yoru /etc/ipsec.conf please

**Comment by rrands1** [comment]
Here you go!  :)
[ipsec.conf.txt](https://github.com/xelerance/Openswan/files/1128904/ipsec.conf.txt)

**Comment by shussain** [comment]
I get a "<Code>SignatureDoesNotMatch</Code>" XML error message.

Can you please make it accessible via pastebin or github Gist?

**Comment by rrands1** [comment]
Sorry about that - how's this:  https://pastebin.com/e8CguTj3

**Comment by shussain** [comment]
I see there is some copy/paste of the ipsec.conf
* please remove 76-95
* un-indent the line _include /etc/ipsec.d/*.conf_

**Comment by shussain** [comment]
I believe the above should fix your immediate issue.

As an aside, you are using Libreswan. If you wish, you can download the [latest version of Openswan](https://github.com/xelerance/Openswan/releases/tag/v2.6.49.1) and compile it.

**Comment by rrands1** [comment]
you = da man!  :)  that worked - thank you very much!  I do have a different issue now - I can't ping (i think the tunnel is not establishing) - the pluto.log has this to say:

packet from <Public IP here>:500: initial Main Mode message received on 10.10.0.181:500 but no connection has been authorized with policy PSK+IKEV1_ALLOW

i am going to research the error over the weekend, but thought i would run it by you in case it was as simple as my other error?

I really appreciate the help!

-randy

**Comment by rrands1** [comment]
also re: Libreswan - i had meant to install OpenSwan - I typed:  yum install Openswan, but i do see the references to Libreswan in the files, too.  Once I get this working, i will have to switch that over - it is what I had intended to put on in the first place...

**Comment by rrands1** [comment]
got it!  I had an IP address (leftIP) incorrect on one side - fixed that, and all working.  THANK YOU again for the help - I appreciate it!
