### ISSUE TITLE
Openswan as Client 

### ISSUE THREAD

**Issue by ririafnita** [xelerance/Openswan#248]
VPN server using Openswan with address 103.19.208.247

Then, i want connect my laptop (CENTOS) with IP 103.19.208.243 to VPN server. Here my configuration:

/etc/ipsec.conf
Code:
   

     config setup
     
     protostack=netkey

    dumpdir=/var/run/pluto

    nat_traversal=yes virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4: 25.0.0.0/8,%v4:100.64.0.0/10,%v6:fd00::/8,%v6:fe80::/10

    conn L2TP-PSK

    authby=secret

    pfs=no

    auto=add

    keyingtries=3

    ikelifetime=8h

    rekey=no

    type=transport

    left=103.19.208.243

    leftprotoport=17/1701

    right=103.19.208.247

    rightprotoport=17/1701

    dpddelay=10

    dpdtimeout=90

    dpdaction=clear

/etc/ipsec.secrets

Code:
 

> 103.19.208.243 103.19.208.247: PSK "vpnku"

/etc/xl2tpd/xl2tpd.conf

Code:

     [lac vpn-connection]

      lns=103.19.208.247

    ppp debug = yes

    pppoptfile = /etc/ppp/options.xl2tpd

    length bit = yes
/etc/ppp/options.xl2tpd

Code:
 

    ipcp-accept-local
    
   ipcp-accept-remote

    require-mschap-v2

    refuse-pap

    ms-dns 8.8.8.8

    noccp

    auth

    crtscts

    idle 1800

    mtu 1410

    mru 1410

    nodefaultroute

    debug

    lock

    proxyarp

    connect-delay 5000

    name lele (myvpn username)

    password nana1234 (my vpn password)

and when i type:ipsec auto --up L2TP-PSK

002 "L2TP-PSK" #10: initiating Quick Mode PSK+ENCRYPT+DONT_REKEY+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW {using isakmp#1 msgid:ed53b5a6 proposal=defaults pfsgroup=no-pfs} 117 "L2TP-PSK" #10: STATE_QUICK_I1: initiate 010 "L2TP-PSK" #10: STATE_QUICK_I1: retransmission; will wait 500ms for response 010 "L2TP-PSK" #10: STATE_QUICK_I1: retransmission; will wait 1000ms for response 010 "L2TP-PSK" #10: STATE_QUICK_I1: retransmission; will wait 2000ms for response 010 "L2TP-PSK" #10: STATE_QUICK_I1: retransmission; will wait 4000ms for response 010 "L2TP-PSK" #10: STATE_QUICK_I1: retransmission; will wait 8000ms for response 010 "L2TP-PSK" #10: STATE_QUICK_I1: retransmission; will wait 16000ms for response 010 "L2TP-PSK" #10: STATE_QUICK_I1: retransmission; will wait 32000ms for response 031 "L2TP-PSK" #10: max number of retransmissions (8) reached STATE_QUICK_I1. No acceptable response to our first Quick Mode message: perhaps peer likes no proposal 000 "L2TP-PSK" #10: starting keying attempt 2 of at most 3, but releasing whack

What should i do to solve this problem to connect my VPNServer?

Thank you

**Comment by shussain** [comment]
what version of Openswan and xl2tpd are you using? 

Can you establish an IPsec tunnel (without using xl2tpd)?

**Comment by ririafnita** [comment]
> what version of Openswan and xl2tpd are you using?
> 
> Can you establish an IPsec tunnel (without using xl2tpd)?

I use openswan-2.6.32-16.el6.i686 . When i connecting my server to client (using windows 7), it works. But, it doesn't works to my  laptop (using centos). I try this tutorial: https://wiki.archlinux.org/index.php/Openswan_L2TP/IPsec_VPN_client_setup

**Comment by shussain** [comment]
What error are you seeing in your logs? You will likely have to enable logs (please look at the /etc/ipsec.conf )

**Comment by ririafnita** [comment]
No error. But when i use windows or ubuntu, my VPN can connect to tunnel.

**Comment by shussain** [comment]
Sorry, I am confused. You stated that you an't establish an Ipsec tunnel using IPsec only but then you say you can connect to the tunnel.

**Comment by shussain** [comment]
@ririafnita  are you still encoutnering problems. Can this ticket be closed?

**Comment by shussain** [comment]
Closing issue. @ririafnita   If this issue is still occuring, then please reopen this issue or create a new issue
