### ISSUE TITLE
How to make openswan as client

### ISSUE THREAD

**Issue by ressyaagung** [xelerance/Openswan#255]
I make a vpn server with openswan. Then, i want my client ( centos ) can connect to openswan. How should i do?

**Comment by shussain** [comment]
Hi. Openswan would be able to do what you need. 

You can refer to the various [examples](https://github.com/xelerance/Openswan/tree/master/programs/examples) here for the connection that you can use. You might want to consider using linux-to-linux. The example uses raw RSA keys but some people prefer to use PSK (pre-shared keys).

**Comment by ressyaagung** [comment]
Thank you. I use L2TP. How's example?

**Comment by shussain** [comment]
There are two examples for l2tp. One is with a [cert](https://github.com/xelerance/Openswan/blob/master/programs/examples/l2tp-cert.conf.in) and one with a [PSK](https://github.com/xelerance/Openswan/blob/master/programs/examples/l2tp-psk.conf.in)

**Comment by ressyaagung** [comment]
Oh i am using PSK, Samir. Then, i want to ask you about why when client access data but can't encrypt?

**Comment by shussain** [comment]
So if I understand you correctly, you have established a l2tp tunnel but it isn't encrypted?

**Comment by ressyaagung** [comment]
Yes. I have established the tunnel but itu isn't encrypted. 

I didn't check my log.  But when i type ipsec verify doesn't have error

**Comment by shussain** [comment]
You will have to enable your logs. _ipsec verify_ is helpful but for troubleshooting you will have to look at your logs. You can enable your logs by opening /etc/ipsec.conf and:
* uncomment plutodebug  The values _contro_l and _parsing_ should be able to give you some basic info.
* un-commenting plutostderrlog You should have your plutostderrlog be set to some file. I like to use /var/log/ipsec.log (be sure to _touch_ the file)

**Comment by shussain** [comment]
Is your issue still occuring? Can I go ahead and close this ticket?

**Comment by shussain** [comment]
Closing ticket. @ressyaagung if this issue is still occuring, please reopen this issue or create a new issue.
