### ISSUE TITLE
Dropping client connection

### ISSUE THREAD

**Issue by Ejz** [xelerance/Openswan#256]
Hi. In my case `ipsec whack --trafficstatus` outputs a list of connections from 1 user from 1 ip (behind NAT). How can i drop a certain connection using whack utlity without dropping another connection?

**Comment by shussain** [comment]
You can down a connection using;
   ipsec auto --down **conn**

**Comment by Ejz** [comment]
```
# ipsec whack --trafficstatus
006 #12: "xauth-psk"[4] 51.18.183.148, username=vpn, type=ESP, add_time=1501158537, inBytes=8713733, outBytes=282325645, lease=192.168.43.10/32
006 #11: "xauth-psk"[5] 51.18.183.148, username=vpn, type=ESP, add_time=1501158069, inBytes=127358, outBytes=404335, lease=192.168.43.11/32
```

You mean like this:

```
# ipsec auto --down xauth-psk[4]
021 no connection named "xauth-psk[4]"
000 terminating all conns with alias='xauth-psk[4]'
021 no connection named "xauth-psk[4]"
```

I need to down just one connection.

**Comment by letoams** [comment]
Down does not work in template/instance conns for a single connection. Deletestate works, but if the other end reconnects again it will just be back online.

If you want to kill a user from reconnecting you can only do it by rejecting their xauth user/password or revoking their certificate

**Comment by Ejz** [comment]
Thx for reply. I noticed that `ipsec whack --deletestate #` doesn't help, client just reconnects. Can `keyingtries=1` be useful in this case?

**Comment by letoams** [comment]
No, the client is told to reconnect when it is disconnected which it does.

You need to explain what you are trying to do. As I said, you need to revoke/remove individual client credentials to stop them from reconnecting

**Comment by Ejz** [comment]
Yap, got ip. Thank you.
