### ISSUE TITLE
How to make my openswan can encrypted

### ISSUE THREAD

**Issue by ririafnita** [xelerance/Openswan#257]
/etc/ipsec.conf:

version 2

#Manual:     ipsec.conf.5

#basic configuration
config setup

   protostack=netkey
   dumpdir=/var/run/pluto/
   nat_traversal=yes
   virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:
25.0.0.0/8,%v4:100.64.0.0/10,%v6:fd00::/8,%v6:fe80::/10

conn L2TP-PSK
   authby=secret
   pfs=yes
   auto=start
   keyingtries=3
   ikelifetime=8h
   keylife=1h
   ike=aes256-sha1;modp1024!
   phase2alg=aes256-sha1;modp1024
   rekey=no
   type=tunnel
   left=%defaultroute
           leftid=103.19.208.244
leftsubnet=192.168.122.0/24
   right=%any
   rightprotoport=17/1701
   dpddelay=10
   dpdtimeout=90
   dpdaction=clear

/etc/ipsec.secrets:

include /etc/ipsec.d/*.secrets
103.19.208.244   %any:   PSK   "vpnku"

/etc/xl2tpd/xl2tpd.conf:
[global]
listen-addr=103.19.208.244
ipsec saref = yes
force userspace = yes

[lns default]
ip range = 192.168.1.2-192.168.1.254
local ip = 192.168.1.1
refuse pap = yes
require authentication = yes
ppp debug = yes
pppoptfile = /etc/ppp/options.xl2tpd
length bit = yes

/etc/ppp/chap-secrets:
#Secrets for authentication using CHAP
#client   server   secret         IP addresses
lili      l2tpd   R1R11234567891234        *

Scenario:

Server (103.19.208.240) have 2 virtual server using KVM, they are VPN
server and ftp server. For VPN server using bridge from server ( bridge:br0
rctl setting with rctlxx /i'm forget about it but i choose rctl/) and for
FTP server and VPN server, i choose virbr0. virbr0 give dhcp for iP private
with network 192.168.122.0/24.

Client connect to vpn server (103.19.208.244) with ip 103.19.208.243 and
then, VPN server give ip 192.168.1.2 to client.  After connect to VPN
server, i will access 192.168.122.20/24 for access data from FTP. Attacker
will do passive sniffing for look ftp data with wireshark and port
mirroring. Switch using Cisco.

Problem:
1. How to make my client (192.168.1.2/32) can access ftp server (
192.168.122.20/24)?

2. How to make my FTP data can't be sniffing my attacker when i access FTP
data?

I am using  openswan-2.6.32-37.el6.i686.rpm.

The topology is : http://uploads.im/6B9Ee.jpg

**Comment by shussain** [comment]
In an earlier discussion, you had mentioned that the l2tp can be dsiabled. Can you please:
*  comment out rightprotoport
* remove the _(IP.vpn server)_ text  from your leftid
* stop xl2tpd service

Can you confirm that you can establish an IPsec tunnel between your left and right sides (103.19.208.244 <-->  103.19.208.243 


If you can't, please enable logging and look at the logs for any errors or issues.

**Comment by ririafnita** [comment]
Okay Samir. I will do it later and give the logs for any errors and issues.

**Comment by ririafnita** [comment]
> In an earlier discussion, you had mentioned that the l2tp can be disabled. Can you please:
> 
> comment out rightprotoport
> remove the (IP.vpn server) text from your leftid
> stop xl2tpd service
> Can you confirm that you can establish an IPsec tunnel between your left and right sides (103.19.208.244 <--> 103.19.208.243
> 
> If you can't, please enable logging and look at the logs for any errors or issues.



I can't establish ipsec tunnel after xl2tpd stoples.

The error from client (using windows) is error 809 the error said i can't established because remote server isnot responding. 

And when i read the log from pluto.log is: http://uploads.im/6lUTd.jpg

**Comment by shussain** [comment]
Can you please post your new ipsec.conf and ipsec.secrets

In addition if you down your ipsec connect (sudo ipsec auto --down _connectionName_), can the hosts ping each other?

**Comment by shussain** [comment]
Actually if you could provide a pastebin link to the output of your _ipsec barf_ that would be ideal

**Comment by ririafnita** [comment]
> Can you please post your new ipsec.conf and ipsec.secrets
> 
> In addition if you down your ipsec connect (sudo ipsec auto --down connectionName), can the hosts ping each other?


/etc/ipsec.conf:

version 2

#Manual: ipsec.conf.5

#basic configuration
config setup
plutostderrlog=/var/log/ipsec.log
plutodebug="all" 
plutodebug="control parsing"
protostack=netkey
dumpdir=/var/run/pluto/
nat_traversal=yes
virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:
25.0.0.0/8,%v4:100.64.0.0/10,%v6:fd00::/8,%v6:fe80::/10

conn L2TP-PSK
authby=secret
pfs=yes
auto=start
keyingtries=3
ikelifetime=8h
keylife=1h
ike=aes256-sha1;modp1024!
phase2alg=aes256-sha1;modp1024
rekey=no
type=tunnel
left=%defaultroute
leftid=103.19.208.244
leftsubnet=192.168.122.0/24
right=%any
dpddelay=10
dpdtimeout=90
dpdaction=clear

/etc/ipsec.secrets:

include /etc/ipsec.d/*.secrets
103.19.208.244 %any: PSK "vpnku"

**Comment by shussain** [comment]
A couple of things to note: You have _plutodebug="all"_ and _plutodebug="control parsing"_  I would suggest for now, you comment out _plutodebug="all"_ 

I will await the output of ipsec barf

**Comment by ririafnita** [comment]
A couple of things to note: You have plutodebug="all" and plutodebug="control parsing" I would suggest for now, you comment out plutodebug="all"

I will await the output of ipsec barf for yoru ipsec barf

https://pastebin.com/C0xbSkKw

**Comment by shussain** [comment]
@ririafnita can you please do the following:

1) make the output of: _sudo ipsec barf_ available in pastebin
2) Update and provide your new network diagram

**Comment by shussain** [comment]
@ririafnita Has your issue been resolved? Can I go ahead and close this ticket?

**Comment by shussain** [comment]
Closing ticket. @ririafnita if you are still having issues, please reopen this ticket or create a new issue.
