### ISSUE TITLE
Roadwarrior with multiple left-subnets is not working in Openswan.

### ISSUE THREAD

**Issue by SumitParashari** [xelerance/Openswan#260]
I am using openswan for a roadwarrior config. With single leftsubnet its working but when I add multiple subnets it doesn't work.
This is my ipsec.conf

config setup
    uniqueids=no
    nat_traversal=yes
    # THIS SETTING MUST BE CORRECT or almost nothing will work;
conn rw4
    keyexchange=ike
    forceencaps=no
    left=66.6.6.2
    leftsubnets=10.200.20.0/24,20.20.20.0/24
    leftupdown=/etc/ipsec.d/rw4.updown
    right=%any
    rightsubnets=vhost:%no,%priv,%v4:10.200.20.0/24,%v4:20.20.20.0/24
    ike=aes-sha1
    esp=aes-sha1
    ikelifetime=60m
    keylife=60m
    pfs=no
    auth=esp
    auto=add
    authby=secret
    dpddelay=30
    dpdtimeout=120
    dpdaction=hold

Please let me know if I am missing something here.
Thanks.

**Comment by letoams** [comment]
On Mon, 21 Aug 2017, SumitParashari wrote:

you cannot use:

rightsubnets=vhost:%no,%priv,%v4:10.200.20.0/24,%v4:20.20.20.0/24

you have to use:

rightsubnets=10.200.20.0/24,20.20.20.0/24

libreswan did fix some issues like --route not being called for all
subnets, and some issues with shared phase1 IKE SA's, so if this
doesn't fix your problem, you should give libreswan a go.

Paul
