### ISSUE TITLE
No acceptable response to our first Quick Mode message: perhaps peer likes no proposal

### ISSUE THREAD

**Issue by Jacky1207** [xelerance/Openswan#261]
hi all.
i want to startup a client with openswan2.6.50. here is my config.

version 2.0  

config setup

        plutodebug="all"
        dumpdir=/var/run/pluto/
        nat_traversal=no
        oe=off
        protostack=auto
        interfaces="ipsec0=ppp0"
        nhelpers=0
conn gprs

        left=%defaultroute
        leftid=@f11787
        rightid=120.234.18.2
        right=120.234.18.2
        rightsubnet=192.125.155.1/24
        keyingtries=3
        type=tunnel
        authby=secret
        pfs=no
        aggrmode=no
        keyexchange=ike
        auth=esp
        auto=add
        ikelifetime=8h
        keylife=8h

when i up gprs conn,i got this error

/etc # ipsec auto --up gprs
002 "sample" #1: initiating Main Mode
105 "sample" #1: STATE_MAIN_I1: initiate
003 "sample" #1: received Vendor ID payload [Openswan (this version) 2.6.50 ]
003 "sample" #1: received Vendor ID payload [Dead Peer Detection]
002 "sample" #1: transition from state STATE_MAIN_I1 to state STATE_MAIN_I2
107 "sample" #1: STATE_MAIN_I2: sent MI2, expecting MR2
002 "sample" #1: transition from state STATE_MAIN_I2 to state STATE_MAIN_I3
109 "sample" #1: STATE_MAIN_I3: sent MI3, expecting MR3
003 "sample" #1: received Vendor ID payload [CAN-IKEv2]
002 "sample" #1: Main mode peer ID is ID_FQDN: '@bofh.xelerance.com'
002 "sample" #1: transition from state STATE_MAIN_I3 to state STATE_MAIN_I4
004 "sample" #1: STATE_MAIN_I4: ISAKMP SA established {auth=OAKLEY_PRESHARED_KEY oursig= theirsig= cipher=aes_128 prf=oakley_sha group=modp2048}
002 "sample" #2: initiating Quick Mode PSK+ENCRYPT+TUNNEL+UP+IKEv2ALLOW+SAREFTRACK {using isakmp#1 msgid:fdc41433 proposal=defaults pfsgroup=no-pfs}
118 "sample" #2: STATE_QUICK_I1: initiate
010 "sample" #2: STATE_QUICK_I1: retransmission; will wait 20s for response
010 "sample" #2: STATE_QUICK_I1: retransmission; will wait 40s for response
031 "sample" #2: max number of retransmissions (2) reached STATE_QUICK_I1.  No acceptable response to our first Quick Mode message: perhaps peer likes no proposal
000 "sample" #2: starting keying attempt 2 of at most 3, but releasing whack

here is pluto debug info:

Jan  1 00:01:19 star-linux daemon.err ipsec_setup: Starting Openswan IPsec 2.6.50...
Jan  1 00:01:20 star-linux daemon.err ipsec_setup: Using KLIPS/legacy stack
Jan  1 00:01:21 star-linux user.info kernel: [   81.570000] klips_info:ipsec_init: KLIPS startup, Openswan KLIPS IPsec stack version: 2.6.50
Jan  1 00:01:21 star-linux user.info kernel: [   81.590000] NET: Registered protocol family 15
Jan  1 00:01:21 star-linux user.warn kernel: [   81.680000] registered KLIPS /proc/sys/net
Jan  1 00:01:21 star-linux user.info kernel: [   81.680000] klips_info:ipsec_alg_init: KLIPS alg v=0.8.1-0 (EALG_MAX=255, AALG_MAX=255)
Jan  1 00:01:21 star-linux user.info kernel: [   81.720000] klips_info:ipsec_alg_init: calling ipsec_alg_static_init()
Jan  1 00:01:21 star-linux user.warn kernel: [   81.730000] ipsec_aes_init(alg_type=15 alg_id=12 name=aes): ret=0
Jan  1 00:01:21 star-linux user.warn kernel: [   81.730000] ipsec_aes_init(alg_type=14 alg_id=9 name=aes_mac): ret=0
Jan  1 00:01:21 star-linux user.warn kernel: [   81.800000] ipsec_3des_init(alg_type=15 alg_id=3 name=3des): ret=0
Jan  1 00:01:22 star-linux user.info kernel: [   82.020000] KLIPS cryptoapi interface: alg_type=15 alg_id=12 name=cbc(aes) keyminbits=128 keymaxbits=256, found(0)
Jan  1 00:01:22 star-linux user.info kernel: [   82.240000] KLIPS: lookup for ciphername=cbc(twofish): not found 
Jan  1 00:01:22 star-linux user.info kernel: [   82.330000] KLIPS: lookup for ciphername=cbc(serpent): not found 
Jan  1 00:01:22 star-linux user.info kernel: [   82.480000] KLIPS: lookup for ciphername=cbc(cast5): not found 
Jan  1 00:01:22 star-linux user.info kernel: [   82.570000] KLIPS: lookup for ciphername=cbc(blowfish): not found 
Jan  1 00:01:22 star-linux user.info kernel: [   82.610000] KLIPS cryptoapi interface: alg_type=15 alg_id=3 name=cbc(des3_ede) keyminbits=192 keymaxbits=192, found(0)
Jan  1 00:01:22 star-linux daemon.err ipsec_setup: KLIPS debug `none'
Jan  1 00:01:22 star-linux user.warn kernel: [   82.950000] 
Jan  1 00:01:23 star-linux daemon.err ipsec_setup: KLIPS ipsec0 on ppp0 10.67.83.3/ pointtopoint 192.168.254.254/32 mtu 1500
Jan  1 00:01:23 star-linux daemon.err ipsec_setup: ipsec0 -> NULL mtu=0(0) -> 0
Jan  1 00:01:24 star-linux authpriv.err ipsec__plutorun: Starting Pluto subsystem...
Jan  1 00:01:24 star-linux daemon.err ipsec_setup: ...Openswan IPsec started
Jan  1 00:01:24 star-linux user.warn syslog: adjusting ipsec.d to /etc/ipsec.d
Jan  1 00:01:24 star-linux user.warn syslog: Labelled IPsec not enabled; value 32001 ignored.
Jan  1 00:01:24 star-linux daemon.err ipsec__plutorun: 002 adding connection: "gprs"
Jan  1 00:01:24 star-linux daemon.err ipsec__plutorun: 002 adding connection: "sample"
Jan  1 00:01:25 star-linux daemon.err ipsec__plutorun: 002 listening for IKE messages
Jan  1 00:01:25 star-linux daemon.err ipsec__plutorun: 002 adding interface ipsec0/ppp0 10.67.83.3:500
Jan  1 00:01:25 star-linux daemon.err ipsec__plutorun: 002 loading secrets from "/etc/ipsec.secrets"

tks for any suggestion

**Comment by letoams** [comment]
On Tue, 17 Oct 2017, Jacky1207 wrote:

The other end does not like your leftsunet= and/or rightsubnet= value,
or your PFS setting.

Paul

**Comment by Jacky1207** [comment]
hi @letoams tks for your reply.

here is my network 
gprs<==================> 120.234.18.2<----------->192.125.155.1/24

as this situation what should i config with  leftsubnet、rightsubnet、rightnexthop and leftnexthop
