### ISSUE TITLE
does openswan work fine in kernel 3.10.X

### ISSUE THREAD

**Issue by Jacky1207** [xelerance/Openswan#262]
hi everyone：
i want to using openswan with linux-3.10.X， if anyone ever success on linux-3.X？

**Comment by Jacky1207** [comment]
in openswan-2.6.50， i found this in README：

A recent Linux distribution based on either Kernel 2.4.x, or 2.6.x are the currently supported platforms.

**Comment by jumpleimy** [comment]
you can try to use openswan-2.6.40. I can use successfully on linux-3.6.10.
