### ISSUE TITLE
How to achieve IPSEC VPN in user mode？

### ISSUE THREAD

**Issue by jumpleimy** [xelerance/Openswan#263]
Whether openswan can achieve IPSEC in user mode? I need to implement IPSEC with User State Protocol Stack, so  what  method can I use ?

**Comment by mcr** [comment]
jumpleimy <notifications@github.com> wrote:
    > Whether openswan can achieve IPSEC in user mode? I need to implement
    > IPSEC with User State Protocol Stack, so what method can I use ?

I suggest you look at Strongswan's libipsec.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [
