### ISSUE TITLE
Lost connection to VPN host after starting Openswan service

### ISSUE THREAD

**Issue by sdmorel** [xelerance/Openswan#266]
Hello, 
I'm having a really strange issue with an Openswan configuration.
This is an AWS EC2 instance inside a VPC. The configuration is as follows:
```
config setup
        # Debug-logging controls:  "none" for (almost) none, "all" for lots.
        plutodebug="all"
        plutostderrlog=/var/log/openswan.log
        plutoopts="--perpeerlog"
        dumpdir=/var/run/pluto/
        # klipsdebug=none
        # plutodebug="control parsing"
        # For Red Hat Enterprise Linux and Fedora, leave protostack=netkey
        protostack=netkey
        nat_traversal=yes
        #virtual_private=
        oe=off
        # Enable this if you see "failed to find any available worker"
        # nhelpers=0
        keep_alive=10
conn myvpn
    type=tunnel
    authby=secret
    left=%defaultroute
    leftsourceip=192.168.1.10
    leftid=<my_public_ip>
    leftsubnets={192.168.1.0/24 192.168.2.0/24 192.168.3.0/24}
    leftnexthop=%defaultroute
    right=<their_public_ip>
    rightid=<their_public_ip>
    rightsubnets={10.20.0.0/16 10.21.30.0/24}
    rightnexthop=<their_public_ip>
    ike=3des-sha1;modp1024!
    esp=3des-sha1
    pfs=no
    auto=start
    compress=no
    aggrmode=no
    ## Phase 1 Lifetime
    ikelifetime=86400s
    ## Phase 2 keylife
    keylife=3600s
    dpddelay=30
    dpdtimeout=120
    dpdaction=restart_by_peer
```
Before starting the ipsec service, I have these routes:
```
Destination            Gateway         Genmask            Flags  Metric Ref    Use Iface
0.0.0.0                  192.168.1.1      0.0.0.0                  UG     0      0        0 eth0
169.254.169.254  0.0.0.0              255.255.255.255  UH     0      0        0 eth0
192.168.1.0          0.0.0.0              255.255.255.0      U        0      0        0 eth0
```
The issue is, after starting the ipsec service I see a new route for the 192.168.0.0/16 network which overlaps with the current route for 192.168.1.0/24
**At that moment, I lose all connectivity with the EC2 instance until I stop and start it again.**
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1      0.0.0.0         UG    0      0        0 eth0
169.254.169.254 0.0.0.0       255.255.255.255 UH    0      0        0 eth0
192.168.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0
192.168.1.0      0.0.0.0         255.255.255.0   U     0      0        0 eth0
10.20.0.0      172.19.1.1      255.255.0.0     UG    0      0        0 eth0
10.21.30.0     172.19.1.1      255.255.255.0   UG    0      0        0 eth0
```
Can you help me with this?
I don't see a configuration parameter to stop Pluto from inserting that overlapping route.

I'm using
> Linux Openswan U2.6.37/K4.9.58-18.55.amzn1.x86_64 (netkey)
> See `ipsec --copyright' for copyright information.

**Comment by letoams** [comment]
On Tue, 14 Nov 2017, Sergio David Morel wrote:

> This is an AWS EC2 instance inside a VPC. The configuration is as follows:
> 
> config setup
[...]
>         # For Red Hat Enterprise Linux and Fedora, leave protostack=netkey
>         protostack=netkey

Note that this comment suggests you are using rhel/centos/fedora, which
has obsoleted openswan for libreswan.

> conn myvpn

>     leftsourceip=192.168.1.10

>     leftsubnets={192.168.1.0/24 192.168.2.0/24 192.168.3.0/24}

Don't use sourceip= if you have multiple subnets.

>     rightsubnets={10.20.0.0/16 10.21.30.0/24}

> Before starting the ipsec service, I have these routes:
> 
> Destination            Gateway         Genmask            Flags  Metric Ref    Use Iface
> 0.0.0.0                  192.168.1.1      0.0.0.0                  UG     0      0        0 eth0
> 169.254.169.254  0.0.0.0              255.255.255.255  UH     0      0        0 eth0
> 192.168.1.0          0.0.0.0              255.255.255.0      U        0      0        0 eth0
> 
> The issue is, after starting the ipsec service I see a new route for the 192.168.0.0/16 network which overlaps with the current
> route for 1922.168.1.0/24

I would not know where your 192.168.0.0/16 would come from, since your
config has no such subnet defined.

Paul

**Comment by sdmorel** [comment]
@letoams Thanks for the reply.
>Don't use sourceip= if you have multiple subnets.
I tried commenting that line and it works!

But it wasn't clear from reading the ipsec.conf manual that you don't use sourceip when having multiple subnets. It would be great to update the documentation stating that.

Also, I find it strange that there are no routes for the 10.20.0.0/16 and 10.21.30.0/24 when the service is started, but I can ping machines in the remote network so it's all fine.

Thanks for your time.

**Comment by letoams** [comment]
netkey does not use routing.

I don’t maintain/release openswan since 2011, so maybe someone else can fix the man page 😜
