### ISSUE TITLE
Unable to hit my SQL Server Instance behind the OpenSwan VPN

### ISSUE THREAD

**Issue by hariprasad-theniah** [xelerance/Openswan#334]
Hey Guys,
I am an ETL Developer and I am pretty new to networking. We have to setup an VPN connection between our AWS EC2 Linux instance and 1 of our clients SQL Server Instance. To test the VPN setup I have initiated 4 EC2 Instances 2 in California Region(1 in Public Subnet and another in Private Subnet) and 2 in Canada Region (1 in Public Subnetand another in Private Subnet). The setup is working fine for SSH between EC2 instances between regions. I have initiated a private SQL server instance(30.0.128.161) in Canada region to test database connectivity, that's where the problem arises

my connection configuration files
conn vpn_conn_1  # Canada VPN                               conn vpn_conn_1  # California VPN
        type=tunnel                                                                      type=tunnel
        authby=secret                                                                  authby=secret
        pfs=yes                                                                             pfs=yes
        auto=start                                                                        auto=start
        keyexchange=ike                                                             keyexchange=ike
        ike=aes192-sha1                                                             ike=aes192-sha1
        esp=aes192-sha1                                                            esp=aes192-sha1
        salifetime=43200s                                                           salifetime=43200s
        left=30.0.0.179                                                                left=176.0.0.122
        leftid=#CANADA Elastic IP#                                           leftid=#CALIFORNIA Elastic IP#
        leftnexthop=%defaultroute                                            leftnexthop=%defaultroute
        leftsubnet=30.0.0.0/16                                                   leftsubnet=176.0.0.0/16
        leftsourceip=30.0.128.143                                             leftsourceip=176.0.0.122
        right=#CALIFORNIA Elastic IP#                                    right=#CANADA Elastic IP#
        rightsubnet=176.0.0.0/16                                             rightid=#CANADA Elastic IP#
        rightid=#CALIFORNIA Elastic IP#                                 rightsubnet=30.0.0.0/16
        rightsourceip=176.0.0.122                                           rightsourceip=30.0.128.143
        rightnexthop=%defaultroute                                      rightnexthop=%defaultroute
        compress=no                                                              compress=no

![image](https://user-images.githubusercontent.com/37882471/45307479-1d805a80-b4ed-11e8-9955-7714d951e531.png)

![image](https://user-images.githubusercontent.com/37882471/45308124-bebbe080-b4ee-11e8-897c-8f393da47cb7.png)

I tried even by changing the source ip to the SQL Server IP, In this case I am able to ping the server but its treated as regular server rather than a database server. I am not able to connect to the SQL Server from Canada Instance itself

There are no machine specific firewall rules.

Kindly help me if i am missing any configuration details to hit database services.  

Thanks

**Comment by mcr** [comment]
hariprasad-theniah <notifications@github.com> wrote:
    > I tried even by changing the source ip to the SQL Server IP, In this
    > case I am able to ping the server but its treated as regular server
    > rather than a database server. I am not able to connect to the SQL
    > Server from Canada Instance itself

What does it mean, that it is treated as a regular server?
In your examples, you seem to use 30.x addresses.
I don't really understand that, I'd think you'd be using 176.x addresses?
(Are any of these addressese real?)

**Comment by hariprasad-theniah** [comment]
Issue Resolved
