### ISSUE TITLE
typo in debian/changelog file 

### ISSUE THREAD

**Issue by fleish** [xelerance/Openswan#336]
@shussain Not a huge deal, but FYI the debian/changelog file in the https://github.com/xelerance/Openswan/releases/tag/v2.6.51 release has a typo that causes errors in the debuild process.

The file ends on line 5 with:

>  -- Samir Hussain <shussain@xelerance.com>  Fridayy, 14 Sept 2018 13:14:16 -0400

But it should read:

 -- Samir Hussain <shussain@xelerance.com>  Friday, 14 Sept 2018 13:14:16 -0400

**Comment by shussain** [comment]
Thank you for the tip @fleish . Updated master and debian-sid branches.
