### ISSUE TITLE
2.6.51 (2.6.51.1) ipsec__plutorun: Segmentation fault over different hardware

### ISSUE THREAD

**Issue by AnatoliChe** [xelerance/Openswan#343]
Hi!
I migrate to 2.6.51.1 on 4 different servers (differen hw, different location, different configurations). And now have problems on each of it every 2-3 days.
Can see in log:
Nov 25 23:04:41 ipsec__plutorun: Segmentation fault
Nov 25 23:04:41 ipsec__plutorun: !pluto failure!:  exited with error status 139 (signal 11)
Nov 25 23:04:41 ipsec__plutorun: restarting IPsec after pause...
Nov 25 23:04:51 ipsec_setup: Stopping Openswan IPsec...

Could you advice how to debug it and find out what the problem exactly?
ipsec --version
Linux Openswan U2.6.51.1/K3.16.59 (netkey)
for build use
make KERNELSRC=/usr/src/linux programs install

**Comment by shussain** [comment]
@AnatoliChe Can you please provide a link to your ipsec barf?

**Comment by missionceo** [comment]
> Hi!
> I migrate to 2.6.51.1 on 4 different servers (differen hw, different location, different configurations). And now have problems on each of it every 2-3 days.
> Can see in log:
> Nov 25 23:04:41 ipsec__plutorun: Segmentation fault
> Nov 25 23:04:41 ipsec__plutorun: !pluto failure!: exited with error status 139 (signal 11)
> Nov 25 23:04:41 ipsec__plutorun: restarting IPsec after pause...
> Nov 25 23:04:51 ipsec_setup: Stopping Openswan IPsec...
> 
> Could you advice how to debug it and find out what the problem exactly?
> ipsec --version
> Linux Openswan U2.6.51.1/K3.16.59 (netkey)
> for build use
> make KERNELSRC=/usr/src/linux programs install

Have you solved the problem?

**Comment by mcr** [comment]
missionceo <notifications@github.com> wrote:
    >> Hi!  I migrate to 2.6.51.1 on 4 different servers (differen hw,
    
> Have you solved the problem?

1) there is a 2.6.51.5 out now.
2) enable core dumps, and send us the back trace and logs privately.
   ("ipsec barf" is a good way to get all the logs, without any private
   keys)

I don't think that this happened.

-- 
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        |    IoT architect   [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by AnatoliChe** [comment]
Hi!
When It's strange situation.
I had error 1-3 times per day.
After it I enabled debug like:
klipsdebug=all
plutodebug=all
plutostderrlog=/dev/shm/openswan.log

After it no one error for months on 10+ servers.

Now I had one server with Linux Openswan U2.6.51.3/K4.9.168 (netkey)
And as only I turned of debug I had
Aug 28 09:30:47 ipsec12.priv kernel: : pluto[22672]: segfault at 1b4 ip 004a32c6 sp bfb2b630 error 4 in pluto[44e000+f8000]
Now it can works fine for some days.

Now days I'm in migrating to U2.6.51.5. 
I already migrated on 3 different servers 
ipsec --version
Linux Openswan U2.6.51.5/K4.9.168 (netkey)
uptime
 10:22:45 up 11 days, 23:08,  1 user,  load average: 0.00, 0.00, 0.00

Those servers don't have high load, and work fine already 28, 11 and 4 days.
So I believe  with U2.6.51.5 problem will gone away. (hope)))

**Comment by AnatoliChe** [comment]
Today I had 
Aug 28 10:54:58 servernp8 kernel: : pluto[7066]: segfault at 1b4 ip 005025c6 sp bfb04ec0 error 4 in pluto[4ad000+f8000]
Openswan
2.6.51.5
And it happened in moment when one Internet channel went down.

**Comment by AnatoliChe** [comment]
still have the problem (
kernel: : pluto[3752]: segfault at 1b4 ip 004e75c6 sp bfa69fc0 error 4 in pluto[492000+f8000]

last what I can see in log 
| started looking for secret for @main.peer->@n1.peer of kind PPK_PSK
| actually looking for secret for @main.peer->@n1.peer of kind PPK_PSK
| line 1: key type PPK_PSK(@main.peer) to type PPK_RSA 
| concluding with best_match=0 lineno=-1
| 4: w->pcw_dead: 0 w->pcw_work: 0 cnt: 11
| asking helper 4 to do compute dh(p2) op on seq: 2402 (len=2672, pcw_work=1)
| crypto helper write of request: cnt=2672<wlen=2672.  
| deleting event for #1929
| inserting event EVENT_CRYPTO_FAILED, timeout in 300 seconds for #1929 
| event added after event EVENT_SA_REPLACE for #1993
| complete state transition with STF_SUSPEND
| * processed 0 messages from cryptographic helpers 
| next event EVENT_DPD in 1 seconds for #1901 (2019-09-23 14:01:51)
| next event EVENT_DPD in 1 seconds for #1901 (2019-09-23 14:01:51)
! helper 4 read 2668+4/2672 bytesfd: 12
! helper 4 doing compute dh(p2) op id: 2402
! calc_dh_shared(): time elapsed (OAKLEY_GROUP_MODP1536): 728 usec
! DH shared-secret:
|  
| helper 4 has finished work (cnt now 1)
| helper 4 replies to id: q#2402
| calling callback function 0x4cd1c0
| quick inI1_outR1: calculated ke+nonce, calculating DH
| processing connection main-n1
| ***emit ISAKMP Hash Payload:
| emitting 20 zero bytes of HASH into ISAKMP Hash Payload
| emitting length of ISAKMP Hash Payload: 24
| HASH(3) computed:  22 cd 95 95  07 00 e4 88  e9 01 79 e2  c8 f9 de de
| HASH(3) computed:  ed dd 57 23
| compute_proto_keymat:needed_len (after ESP enc)=32
| compute_proto_keymat:needed_len (after ESP auth)=52
| ESP KEYMAT 
|   KEYMAT computed:
|   0d ff 35 22  17 00 c1 89  f4 b4 73 55  a1 7c be a0
|   c5 76 11 95  ea ac 28 cb  1e 88 2f 73  0a 26 c5 07
|   2c 2e 75 c9  05 c7 d2 95  43 fa 44 f5  4b 86 d9 02
|   92 3e 13 50
|   Peer KEYMAT computed:
|   30 50 27 02  08 68 e7 0d  aa ea 93 41  42 a5 8f 84
|   da 13 4b 6e  c8 52 c1 89  51 56 e4 13  60 df 91 83
|   1c 6c 8e ce  e9 9a 85 ce  3a 45 de 75  4f 1b 98 d8
|   e9 5e d9 f4
| state #1929: install_ipsec_sa() for inbound and outbound
| route owner of "main-n1" erouted: self; eroute owner: self
| could_route called for main-n1 (kind=CK_PERMANENT)
| state #1929: now setting up incoming SA
pluto_crypto_helper: helper [nonnss] (2) is exiting normally 
pluto_crypto_helper: helper [nonnss] (9) is exiting normally 
pluto_crypto_helper: helper [nonnss] (3) is exiting normally 
pluto_crypto_helper: helper [nonnss] (6) is exiting normally 
pluto_crypto_helper: helper [nonnss] (4) is exiting normally 
pluto_crypto_helper: helper [nonnss] (10) is exiting normally 
pluto_crypto_helper: helper [nonnss] (0) is exiting normally 
pluto_crypto_helper: helper [nonnss] (7) is exiting normally 
pluto_crypto_helper: helper [nonnss] (5) is exiting normally 
pluto_crypto_helper: helper [nonnss] (8) is exiting normally 
pluto_crypto_helper: helper [nonnss] (1) is exiting normally 
Segmentation fault
