### ISSUE TITLE
IPv6-only iOS LT2P client -> IPv4-only server fails to talk

### ISSUE THREAD

**Issue by BradleyMarie** [xelerance/Openswan#398]
I've got an IPv6-only, DNS64 iOS L2TP client (T-Mobile) and an IPv4 Openswan server sitting in my closet at home that are failing to talk with each other.

I see this [error](https://github.com/xelerance/Openswan/blob/0304d6b1d9f4d55285bc3e2e9c530ff5bcaf1e47/programs/pluto/ikev1_quick.c#L459) being reported on the server

"L2TP-PSK-NAT"[2] 172.58.21.103 #1: peer client ID payload ID_IPV4_ADDR is invalid (0.0.0.0) in Quick I1 complete state transition with (null)

This is because iOS isn't sending an ID_IPV4_ADDR identity since it doesn't have one. It is sending an ID_IPV6_ADDR but that ends up getting ignored by Openswan since (at least based on my read of the code) it looks for an identity matching the type of the [subnet the client](https://github.com/xelerance/Openswan/blob/0304d6b1d9f4d55285bc3e2e9c530ff5bcaf1e47/programs/pluto/ikev1_quick.c#L170) is on.

It's not clear to me if this is a bug with Apple's client (which is also OSS) or Openswan, so I've filed bugs in both places. Hopefully this isn't a spec bug.

**Comment by mcr** [comment]
Hi. Do you intend to negotiate a v4 over v6 tunnel, or a v6 over v6 tunnel?
Are you using IKEv1 or IKEv2?

Oh, I see. You want to negotiate from an IPv6 address to an IPv6 target, but through NAT64, so the responder sees IPv4, but the initiator thinks it is IPv6.

There are some additional controls in Openswan to set the inner address family explicitely, but...
I'm surprised you are using an ID_IPV6_ADDR as your identity, as that's gonna change as you move around.  I'd use an FQDN here.
If you are getting as far as the Quick I1, then that must be IKEv1. IKEv2 is much saner and more reliable.  If you are getting to this point, with the L2TP mention, then I guess you are trying to negotiate a transport mode tunnel.  I just don't think it will work with Openswan.
You could try Libreswan or Strongswan; but I suspect that the NAT64 issues might not be resolved there either. Any way, using IKEv2 and not L2TP is a win.

ipsec barf on the target system will sanitize your config of private info and let us see what you are doing, and let us see the rest of the logs.

**Comment by BradleyMarie** [comment]
Looking to negotiate a v4 over a v6 tunnel, I think.

The server here actually is reachable over IPv6, but unfortunately a number of questionable decisions made by the makers of the box (a Synology NAS) running the server mean that the VPN server here is only reachable over IPv4. The server can thought of as not having an IPv6 address.

The client thinks it's talking to an IPv6 server because the client gets a synthesized AAAA entry back from the DNS64 server. This is the reason the client ends up sending ID_IPV6_ADDR.

Would it be wrong for the server here to use the ID_IPV6_ADDR it gets from the client?

**Comment by BradleyMarie** [comment]
This Was fixed on the client side in iOS 13.2
