### ISSUE TITLE
CCM/GCM ike_alg_register_enc FAILED

### ISSUE THREAD

**Issue by AnatoliChe** [xelerance/Openswan#422]
Hi!
pluto --nofork    --stderrlog
`ike_alg_register_enc(): Activating aes_ccm_8: Ok (ret=0)
ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
ike_alg_register_enc(): Activating aes_ccm_12: FAILED (ret=-17)
ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
ike_alg_register_enc(): Activating aes_ccm_16: FAILED (ret=-17)
ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
ike_alg_register_enc(): Activating aes_gcm_8: FAILED (ret=-17)
ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
ike_alg_register_enc(): Activating aes_gcm_12: FAILED (ret=-17)
ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
ike_alg_register_enc(): Activating aes_gcm_16: FAILED (ret=-17)
`

after commit [3217ce9](https://github.com/xelerance/Openswan/pull/420/commits/3217ce9c5c462259568837ae2e2ff9e9b9f13ad7)

`ike_alg_register_enc(): Activating aes_ccm_8: Ok (ret=0)
ike_alg_register_enc(): Activating aes_ccm_12: Ok (ret=0)
ike_alg_register_enc(): Activating aes_ccm_16: Ok (ret=0)
ike_alg_register_enc(): Activating aes_gcm_8: Ok (ret=0)
ike_alg_register_enc(): Activating aes_gcm_12: Ok (ret=0)
ike_alg_register_enc(): Activating aes_gcm_16: Ok (ret=0)
`
Could you merge this patch or rewrite code?

ps
It's not possible to use GCM with OSW but after this patch it's possible to register algo.

**Comment by mcr** [comment]
Anatoli <notifications@github.com> wrote:
`   > ps It's not possible to use GCM with OSW but after this patch it's
    > possible to register algo.

There are significant changes to this part of the code, and those issues are
already resolved.
 
I'm about ten unit test case failures to fix away from commiting that.
It will be 2.6.53 or 2.7.0, TBD.

-- 
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        |    IoT architect   [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by AnatoliChe** [comment]
That's Great!
So you don't need my ugly patches to do:
 STATE_QUICK_I2: sent QI2, IPsec SA established transport mode {ESP=>0x2a5fe6ef <0x8878fac4 xfrm=AES_GCM_C_160-NONE NATOA=none NATD=none DPD=enabled}

Congratulations with 2.6.52 release and Happy New Year!

Thanks for your work.

**Comment by shussain** [comment]
Thank you for all the commits @AnatoliChe  and hope you also have a good New Year
