### ISSUE TITLE
ikev2 ah issue

### ISSUE THREAD

**Issue by lijianming002** [xelerance/Openswan#426]
I'm running Openswan 2.6.51.5 between two Ubuntu

but it seems it always restart when i set like this:

Ubuntu1:
config setup
   dumpdir=/var/run/pluto/
   nat_traversal=yes
   oe=off
   protostack=netkey
   keep_alive=60
   plutodebug="crypt parsing control lifecycle pfkey dpd dns oppo oppoinfo"
conn IPSec_TUN_2
   type=tunnel
 #SA configuration
   pfs=no
   phase2=ah
   phase2alg=md5
   salifetime=28800s
   dpdaction=restart_by_peer
   dpddelay=60
   dpdtimeout=180
 #IKE configuration
   ikev2=insist
   authby=secret
   ike=3des-sha2_256;modp1024
   ikelifetime=86400s
 #Left configuration
   left=172.16.14.203
   leftsubnet=192.168.30.0/24
   leftid=172.16.14.203
   leftupdown="ipsec_updown 1"
 #Right configuration
   right=172.16.14.104
   rightsubnet=192.168.104.0/24
   rightid=172.16.14.104
   auto=start

Ubuntu2：
config setup
   dumpdir=/var/run/pluto/
   nat_traversal=yes
   oe=off
   protostack=netkey
   keep_alive=60
   plutodebug="crypt parsing control lifecycle pfkey dpd dns oppo oppoinfo"
conn IPSec_TUN_2
   type=tunnel
 #SA configuration
   pfs=no
   phase2=ah
   phase2alg=md5
   salifetime=28800s
   dpdaction=restart_by_peer
   dpddelay=60
   dpdtimeout=180
 #IKE configuration
   ikev2=insist
   authby=secret
   ike=3des-sha2_256;modp1024
   ikelifetime=86400s
 #Left configuration
   left=172.16.14.104
   leftsubnet=192.168.104.0/24
   leftid=172.16.14.104
   leftupdown="ipsec_updown 1"
 #Right configuration
   right=172.16.14.203
   rightsubnet=192.168.30.0/24
   rightid=172.16.14.203
   auto=start

**Comment by lijianming002** [comment]
the log is as follows:

Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: using secrets file: /etc/ipsec.secrets
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: %myid = (none)
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: debug crypt+parsing+control+lifecycle+dns+oppo+pfkey+dpd+oppoinfo
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: virtual_private (%priv):
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: - allowed 0 subnets: 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: - disallowed 0 subnets: 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: WARNING: Either virtual_private= is not specified, or there is a syntax 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2:          error in that line. 'left/rightsubnet=vhost:%priv' will not work!
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: WARNING: Disallowed subnets in virtual_private= is empty. If you have 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2:          private address space in internal use, it should be excluded!
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=2, name=ESP_DES, ivlen=8, keysizemin=64, keysizemax=64
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=3, name=ESP_3DES, ivlen=8, keysizemin=192, keysizemax=192
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=11, name=ESP_NULL, ivlen=0, keysizemin=0, keysizemax=0
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=12, name=ESP_AES, ivlen=8, keysizemin=128, keysizemax=256
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=13, name=ESP_AES_CTR, ivlen=8, keysizemin=160, keysizemax=288
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=14, name=ESP_AES_CCM_A, ivlen=8, keysizemin=128, keysizemax=256
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=15, name=ESP_AES_CCM_B, ivlen=8, keysizemin=128, keysizemax=256
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=16, name=ESP_AES_CCM_C, ivlen=8, keysizemin=128, keysizemax=256
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=18, name=ESP_AES_GCM_A, ivlen=8, keysizemin=160, keysizemax=288
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=19, name=ESP_AES_GCM_B, ivlen=12, keysizemin=160, keysizemax=288
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP encrypt: id=20, name=ESP_AES_GCM_C, ivlen=16, keysizemin=160, keysizemax=288
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP auth attr: id=1, name=AUTH_ALGORITHM_HMAC_MD5, keysizemin=128, keysizemax=128
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP auth attr: id=2, name=AUTH_ALGORITHM_HMAC_SHA1, keysizemin=160, keysizemax=160
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP auth attr: id=5, name=AUTH_ALGORITHM_HMAC_SHA2_256, keysizemin=256, keysizemax=256
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP auth attr: id=6, name=AUTH_ALGORITHM_HMAC_SHA2_384, keysizemin=384, keysizemax=384
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP auth attr: id=7, name=AUTH_ALGORITHM_HMAC_SHA2_512, keysizemin=512, keysizemax=512
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm ESP auth attr: id=251, name=AUTH_ALGORITHM_NULL_KAME, keysizemin=0, keysizemax=0
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE encrypt: id=0, name=(null), blocksize=16, keydeflen=131
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE encrypt: id=5, name=OAKLEY_3DES_CBC, blocksize=8, keydeflen=192
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE encrypt: id=7, name=OAKLEY_AES_CBC, blocksize=16, keydeflen=128
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE hash: id=1, name=OAKLEY_MD5, hashsize=16
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE hash: id=2, name=OAKLEY_SHA1, hashsize=20
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE hash: id=4, name=OAKLEY_SHA2_256, hashsize=32
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE hash: id=6, name=OAKLEY_SHA2_512, hashsize=64
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=1, name=OAKLEY_GROUP_MODP768, bits=768
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=2, name=OAKLEY_GROUP_MODP1024, bits=1024
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=5, name=OAKLEY_GROUP_MODP1536, bits=1536
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=14, name=OAKLEY_GROUP_MODP2048, bits=2048
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=15, name=OAKLEY_GROUP_MODP3072, bits=3072
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=16, name=OAKLEY_GROUP_MODP4096, bits=4096
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=17, name=OAKLEY_GROUP_MODP6144, bits=6144
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=18, name=OAKLEY_GROUP_MODP8192, bits=8192
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=22, name=OAKLEY_GROUP_DH22, bits=1024
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=23, name=OAKLEY_GROUP_DH23, bits=2048
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: algorithm IKE dh group: id=24, name=OAKLEY_GROUP_DH24, bits=2048
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: stats db_ops: {curr_cnt, total_cnt, maxsz} :context={0,2,36} trans={0,2,72} attrs={0,2,96} 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2": 192.168.30.0/24===172.16.14.203...172.16.14.167===192.168.0.0/24; prospective erouted; eroute owner: #0
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2":     myip=unset; hisip=unset; myup=ipsec_updown 2;
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2":   ike_life: 86400s; ipsec_life: 28800s; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 0 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2":   policy: PSK+AUTHENTICATE+TUNNEL+UP+!IKEv1+IKEv2ALLOW+IKEv2Init+SAREFTRACK; prio: 24,24; interface: wan; kind=CK_PERMANENT
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2":   dpd: action:restart_by_peer; delay:60; timeout:180;  
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2":   newest ISAKMP SA: #2; newest IPsec SA: #0; eroute owner: #0;
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2":   IKE algorithms wanted: 3DES_CBC(5)_000-SHA2_256(4)_000-MODP1024(2); flags=-strict
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2":   IKE algorithms found:  3DES_CBC(5)_192-SHA2_256(4)_256-MODP1024(2)
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2":   IKE algorithm newest: BLOWFISH_CBC_192-SHA2_384-MODP1024
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2":   AH algorithms wanted: MD5(1)_000; flags=-strict
Jan 14 18:57:18 router authpriv.debug pluto[2662]: | kernel_alg_esp_auth_keylen(auth=1, sadb_aalg=2): a_keylen=16
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: "IPSec_TUN_2":   AH algorithms loaded: MD5(1)_128
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: #1: "IPSec_TUN_2":500 IKEv2.0 STATE_PARENT_I1 (sent v2I1, expected v2R1); EVENT_v2_RETRANSMIT in 35s; nodpd; retranscnt=0,outorder=0,last=-1,next=1,recv=-1; msgid=0; idle; import:admin initiate
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: #3: "IPSec_TUN_2":4500 IKEv2.0 STATE_UNDEFINED ((null)); EVENT_SO_DISCARD in 0s; nodpd; msgid=0; idle; import:respond to friend
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: #2: "IPSec_TUN_2":4500 IKEv2.0 STATE_PARENT_R2 (received v2I2, PARENT SA established); EVENT_SA_REPLACE in 86400s; newest ISAKMP; nodpd; retranscnt=0,outorder=0,last=-1,next=1,recv=0; msgid=0; idle; import:respond to friend
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: 
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: It is now: 1578999438 seconds since epoch
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: event EVENT_SO_DISCARD is schd: 1578999438 (in 0s) state:3
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2:     connection: "IPSec_TUN_2"
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: event EVENT_PENDING_DDNS is schd: 1578999439 (in 1s) state:-1
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: event EVENT_PENDING_PHASE2 is schd: 1578999439 (in 1s) state:-1
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: event EVENT_v2_RETRANSMIT is schd: 1578999473 (in 35s) state:1
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2:     connection: "IPSec_TUN_2"
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: event EVENT_REINIT_SECRET is schd: 1579002919 (in 3481s) state:-1
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: event EVENT_LOG_DAILY is schd: 1579017600 (in 18162s) state:-1
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: event EVENT_SA_REPLACE is schd: 1579085838 (in 86400s) state:2
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2:     connection: "IPSec_TUN_2"
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: ABORT at /home/lijianming/r3000/3.0/build_dir/target-r3000/openswan-2.6.51.5/programs/pluto/timer.c:97
Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: ABORT at /home/lijianming/r3000/3.0/build_dir/target-r3000/openswan-2.6.51.5/programs/pluto/timer.c:97
Jan 14 18:57:19 router daemon.err ipsec__plutorun: Aborted (core dumped)
Jan 14 18:57:19 router authpriv.warn pluto[2666]: pluto_crypto_helper: helper [nonnss] (0) is exiting normally 
Jan 14 18:57:19 router daemon.err ipsec__plutorun: !pluto failure!:  exited with error status 134 (signal 6)
Jan 14 18:57:19 router daemon.err ipsec__plutorun: restarting IPsec after pause...

**Comment by AnatoliChe** [comment]
> I'm running  **Openswan 2.6.52**  between two Ubuntu
> Jan 14 18:57:18 router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: ABORT at /home/lijianming/r3000/3.0/build_dir/target-r3000/**openswan-2.6.51.5**/programs/pluto/timer.c:97

?

**Comment by mcr** [comment]
AnatoliChe <notifications@github.com> wrote:

    >> I'm running **Openswan 2.6.52** between two Ubuntu Jan 14 18:57:18
    >> router authpriv.warn pluto[2662]: "IPSec_TUN_2" #2: ABORT at
    >> /home/lijianming/r3000/3.0/build_dir/target-r3000/**openswan-2.6.51.5**/programs/pluto/timer.c:97

    > ?

That's the name of the directory that it was extracted to.
Did you do this build?  extract from tgz?  Or did you git update?
Maybe the tgz has the wrong directory in it, I haven't checked yet.

**Comment by AnatoliChe** [comment]
> That's the name of the directory that it was extracted to.
That's clear. But I won't be surprised if **lijianming002** running 2.5.51.5 which had problem with DES instead of 2.6.52.
