### ISSUE TITLE
openswan v3.0.0 packaging not working in amazon linux 2023

### ISSUE THREAD

**Issue by EeroV** [xelerance/Openswan#481]
Hi,

with this modification fedora packaging works with amazon linux v2023. 

--- ./Openswan-3.0.0/programs/verify/verify.in  2021-01-22 18:25:50.000000000 +0000
+++ ./Openswan-3.0.0/programs/verify/verify.in.new      2023-03-26 08:57:32.945209151 +0000
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/bin/python3
 #
 # Copyright (C) 2012 Paul Wouters <pwouters@redhat.com>
 #

**Comment by EeroV** [comment]
it's probably wise to add own package directory to amazon linux 2023.

**Comment by letoams** [comment]
Even wiser to switch to an actively developed and maintained implementation such as libreswan or strongswan.Sent using a virtual keyboard on a phoneOn Mar 26, 2023, at 20:26, Eero Volotinen ***@***.***> wrote:﻿
it's probably wise to add own package directory to amazon linux 2023.
