### ISSUE TITLE
ipsec verify fails

### ISSUE THREAD

**Issue by atulatri** [xelerance/Openswan#6]
Hi,

I am using Cetos 6.4. When I run command "ipsec verify" it fails with error "IP XFRM BROKEN".

It seems that issue is in file "openswan-2.6.39/programs/verify/verify.in". In this we are checking for text "XFRM-OBJECT". But on my system error message returned by command "ip xfrm" does not contain text "XFRM-OBJECT", it contains "XFRM_OBJECT" instead.

Please let me know if you need any further information from me on this.

Thanks & Regards,
Atul Atri.

**Comment by gzldx** [comment]
![image](https://cloud.githubusercontent.com/assets/2508193/18624862/3ea4da9a-7e7d-11e6-8f71-518f4ac99499.png)

I update the yum epel repository and running "yum install libreswan", and still get this error. How to fixed it?

**Comment by letoams** [comment]
That's a false positive - back port it from  libreswan for a fix.

Note libreswan has replaced openswan in rhel/cent is 6.9 and higher and rhel/centos 7 has only shipped with libreswan

**Comment by gzldx** [comment]
My CentOS is 6.4.. Can you show me the command? Thank you for your reply!

**Comment by gzldx** [comment]
yum erase libreswan??

**Comment by shussain** [comment]
The issue has been fixed with commit 37d9af0 in the 2.6.50dev branch. It will be merged into master before November 8th and there will be a new release at (or before) that time.
