### ISSUE TITLE
righsubnets keyword causing "023 address family inconsistency in this/that connection"

### ISSUE THREAD

**Issue by deepkamal** [xelerance/Openswan#88]
with this configuration:

conn ets1
        authby=secret
        ikelifetime=86400s
        keylife=86400s
        pfs=no
        auto=start
        ike=3des-sha1;modp1024!
        esp=3des-sha1;
        aggrmode=no
        forceencaps=yes
        left=172.31.3.226
        leftid=X.X.X.X
        leftsourceip=X.X.X.X
        right=X.X.X.X
#       rightid=X.X.X.X
#       rightsubnet=10.161.6.10/32
        rightsubnets={10.161.6.10/32 10.160.176.87/32 10.160.176.88/32 10.160.176.89/32}

I always get this error:

root@ip-172-31-3-226:~# ipsec auto --add ets1
defaulting leftsubnet to X.X.X.X
023 address family inconsistency in this/that connection
037 attempt to load incomplete connection

whereas, if I use rightsubnet instead of rightsubnets it works perfectly, can some one please suggest why rightsubnets is not working for me?

root@ip-172-31-3-226:~# ipsec --version
Linux Openswan U2.6.37/K3.2.0-58-virtual (netkey)
See `ipsec --copyright' for copyright information.

**Comment by shamun** [comment]
```
left=public IP
leftsubnets=public IP/32
```

Solved the problem.
