### ISSUE TITLE
openswan log ERROR

### ISSUE THREAD

**Issue by mcacker** [xelerance/Openswan#92]
We're seeing the following error in our logs for all tunnels:

```
pluto[3048]: ERROR: "tunnel-n" #6: sendto on eth0 to x.x.x.x:500 failed in main_outI1. Errno 22: Invalid argument
```

There doesn't appear to be any further information, and the tunnels get established, however, I would like to know what is causing the error and how to eliminate it.  Does anyone know what the error means and how to fix it?

We're running Openswan 2.6.37 on Amazon Linux in AWS.

thanks, Mitchell

**Comment by shussain** [comment]
Can't reproduce this issue with latest OSW version
